"use client";
import { IncidentCard } from "@/components/incidents/incident-card";
import { IncidentFilters, type IncidentFilterValue } from "@/components/incidents/incident-filters";
import { listIncidents } from "@/features/incidents/service";
import type { IncidentStatus } from "@/features/incidents/types";
import { AlertTriangle, CheckCircle2, Clock3, Plus } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
const tabs:[string,string][]=[["","Todas"],["OPEN","Abiertas"],["IN_PROGRESS","En proceso"],["RESOLVED","Resueltas"]];
export default function SupervisorIncidentsPage(){const [items,setItems]=useState(()=>listIncidents().filter(i=>i.reportedBy==="Juan Rodríguez"));const [filter,setFilter]=useState<IncidentFilterValue>({query:"",tower:"",priority:"",status:"",date:""});useEffect(()=>{const reload=()=>setItems(listIncidents().filter(i=>i.reportedBy==="Juan Rodríguez"));window.addEventListener("adcondo:incidents",reload);return()=>window.removeEventListener("adcondo:incidents",reload)},[]);const shown=items.filter(i=>(!filter.query||`${i.code} ${i.towerName} ${i.title} ${i.description}`.toLowerCase().includes(filter.query.toLowerCase()))&&(!filter.tower||i.towerName===filter.tower)&&(!filter.priority||i.priority===filter.priority)&&(!filter.status||i.status===filter.status)&&(!filter.date||i.createdAt.startsWith(filter.date)));const count=(s:IncidentStatus)=>items.filter(i=>i.status===s).length;return <div className="incidents-page"><div className="dashboard-heading"><div><span className="mobile-overline">Seguimiento</span><h1>Mis incidencias</h1><p>Reporta hallazgos y verifica su solución.</p></div><Link className="btn btn--primary new-incident-button" href="/supervisor/incidencias/nueva"><Plus/>Nueva incidencia</Link></div><section className="incident-kpis"><article><AlertTriangle/><span><b>{count("OPEN")}</b>Abiertas</span></article><article><Clock3/><span><b>{count("IN_PROGRESS")}</b>En proceso</span></article><article><CheckCircle2/><span><b>{count("RESOLVED")}</b>Resueltas</span></article></section><IncidentFilters value={filter} onChange={setFilter} towers={[...new Set(items.map(i=>i.towerName))]}/><div className="incident-tabs">{tabs.map(([value,label])=><button className={filter.status===value?"active":""} key={value} onClick={()=>setFilter({...filter,status:value})}>{label}</button>)}</div><section className="incident-list">{shown.map(item=><IncidentCard key={item.id} incident={item}/>)}</section></div>}
