"use client";
import { IncidentCard } from "@/components/incidents/incident-card";
import { IncidentFilters,type IncidentFilterValue } from "@/components/incidents/incident-filters";
import type { Incident,IncidentStatus } from "@/features/incidents/types";
import { AlertTriangle,CheckCircle2,Clock3,Plus } from "lucide-react";
import Link from "next/link";
import { useEffect,useState } from "react";
const tabs:[[IncidentStatus|"",string],[IncidentStatus|"",string],[IncidentStatus|"",string],[IncidentStatus|"",string]]=[["","Todas"],["OPEN","Abiertas"],["IN_PROGRESS","En proceso"],["RESOLVED","Resueltas"]];
export default function SupervisorIncidentsPage(){const [items,setItems]=useState<Incident[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState<IncidentFilterValue>({query:"",tower:"",priority:"",status:"",date:""});useEffect(()=>{fetch("/api/incidents",{cache:"no-store"}).then(async response=>{const data=await response.json() as {incidents?:Incident[];error?:string};if(!response.ok)throw new Error(data.error);setItems(data.incidents??[])}).catch(reason=>setError(reason instanceof Error?reason.message:"No se pudieron cargar las incidencias.")).finally(()=>setLoading(false))},[]);const shown=items.filter(item=>(!filter.query||`${item.code} ${item.towerName} ${item.title} ${item.description}`.toLowerCase().includes(filter.query.toLowerCase()))&&(!filter.tower||item.towerName===filter.tower)&&(!filter.priority||item.priority===filter.priority)&&(!filter.status||item.status===filter.status)&&(!filter.date||item.createdAt.startsWith(filter.date)));const count=(status:IncidentStatus)=>items.filter(item=>item.status===status).length;return <div className="incidents-page"><div className="dashboard-heading"><div><span className="mobile-overline">Seguimiento</span><h1>Mis incidencias</h1><p>Reporta hallazgos y verifica su solución.</p></div><Link className="btn btn--primary new-incident-button" href="/supervisor/incidencias/nueva"><Plus/>Nueva incidencia</Link></div><section className="incident-kpis"><article><AlertTriangle/><span><b>{count("OPEN")}</b>Abiertas</span></article><article><Clock3/><span><b>{count("IN_PROGRESS")}</b>En proceso</span></article><article><CheckCircle2/><span><b>{count("RESOLVED")}</b>Resueltas</span></article></section><IncidentFilters value={filter} onChange={setFilter} towers={[...new Set(items.map(item=>item.towerName))]}/><div className="incident-tabs">{tabs.map(([value,label])=><button className={filter.status===value?"active":""} key={value} onClick={()=>setFilter({...filter,status:value})}>{label}</button>)}</div>{loading?<section className="card">Cargando incidencias…</section>:error?<p className="form-error">{error}</p>:<section className="incident-list">{shown.length?shown.map(item=><IncidentCard key={item.id} incident={item}/>):<div className="card empty-state"><h2>Sin incidencias</h2><p>No hay registros que coincidan con los filtros.</p></div>}</section>}</div>}
