"use client";
import type { ActivityLog, AppDocument } from "@/features/reports/types";
import { Download, Eye, FileText, Share2, Trash2 } from "lucide-react";
import { removeDocument } from "@/features/reports/service";
export function KpiCard({label,value}:{label:string;value:string|number}){return <article className="report-kpi"><b>{value}</b><span>{label}</span></article>}
export function ChartCard({title,items}:{title:string;items:{label:string;value:number}[]}){const max=Math.max(...items.map(i=>i.value),1);return <section className="card chart-card"><h2>{title}</h2>{items.map(i=><div key={i.label}><span>{i.label}</span><i><b style={{width:`${i.value/max*100}%`}}/></i><strong>{i.value}</strong></div>)}</section>}
export function ActivityTimeline({items}:{items:ActivityLog[]}){return <div className="activity-timeline">{items.map(a=><article key={a.id}><i/><div><b>{a.description}</b><p>{a.userName} · {a.entityType}</p><time>{new Date(a.createdAt).toLocaleString("es-DO")}</time></div></article>)}</div>}
export function ExportActions(){return <div className="export-actions"><button disabled title="Disponible al conectar el backend"><Download/>PDF · Próximamente</button><button disabled title="Disponible al conectar el backend"><Download/>Excel · Próximamente</button><button onClick={()=>navigator.clipboard?.writeText(location.href)}><Share2/>Compartir</button></div>}
export function DocumentCard({document,admin=true,onChange}:{document:AppDocument;admin?:boolean;onChange?:()=>void}){return <article className="document-card"><FileText/><div><b>{document.name}</b><small>{document.category} · {document.towerName??"General"}</small><span>{new Date(document.documentDate).toLocaleDateString("es-DO")} · {document.uploadedBy}</span></div><button disabled={!document.fileUrl} title={document.fileUrl?"Ver documento":"Disponible al conectar Storage"}><Eye/>Ver</button><button disabled={!document.fileUrl} title={document.fileUrl?"Descargar":"Disponible al conectar Storage"}><Download/>Descargar</button>{admin&&<button className="danger" onClick={()=>{removeDocument(document.id);onChange?.()}}><Trash2/>Eliminar</button>}</article>}
