"use client";
import { IncidentPriorityBadge, IncidentStatusBadge } from "@/components/incidents/incident-badges";
import { InventoryStatusBadge, MaterialRequestStatusBadge } from "@/components/inventory/badges";
import { VisitStatusBadge } from "@/components/visits/visit-status-badge";
import type { Incident } from "@/features/incidents/types";
import type { MaterialRequest, TowerInventory } from "@/features/inventory/types";
import type { ActivityLog, AppDocument } from "@/features/reports/types";
import type { Tower, TowerActivity, TowerPhoto } from "@/features/towers/types";
import type { Visit } from "@/features/visits/types";
import { Building2, CalendarDays, CheckCircle2, ShieldAlert, Users, Warehouse } from "lucide-react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { TowerActivityTimeline } from "./tower-activity-timeline";
import { TowerContacts } from "./tower-contacts";
import { TowerDocuments } from "./tower-documents";
import { TowerPhotoGallery } from "./tower-photo-gallery";

type Overview = { visits: Visit[]; incidents: Incident[]; inventory: TowerInventory[]; requests: MaterialRequest[]; documents: AppDocument[]; activity: ActivityLog[] };
const empty: Overview = { visits: [], incidents: [], inventory: [], requests: [], documents: [], activity: [] };
function Empty({ children }: { children: string }) { return <p>{children}</p>; }

export function TowerSummary({ tower, role = "admin" }: { tower: Tower; role?: "admin" | "supervisor" }) {
  const tab = useSearchParams().get("tab") ?? "resumen";
  const [data, setData] = useState<Overview>(empty), [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { let active = true; setLoading(true); fetch(`/api/towers/${tower.id}/overview`, { cache: "no-store" }).then(async (response) => { const result = await response.json() as Overview & { error?: string }; if (!response.ok) throw new Error(result.error ?? "No se pudo cargar el resumen."); if (active) setData(result); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "No se pudo cargar el resumen."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [tower.id]);
  const activity = useMemo<TowerActivity[]>(() => data.activity.map((item) => ({ id: item.id, date: item.createdAt, user: item.userName, action: item.description, entity: item.entityType })), [data.activity]);
  const photos = useMemo<TowerPhoto[]>(() => [...data.incidents.flatMap((incident) => incident.photos.map((photo) => ({ id: photo.id, url: photo.url, date: photo.createdAt, origin: "Incidencia" as const, supervisor: incident.reportedBy }))), ...data.inventory.flatMap((item) => item.photos.map((photo) => ({ id: photo.id, url: photo.url, date: photo.createdAt, origin: "Inventario" as const, supervisor: item.lastCheckedBy ?? "Supervisor" })))], [data.incidents, data.inventory]);
  if (loading) return <section className="card tower-tab-panel">Cargando información real de la torre...</section>;
  if (error) return <section className="card tower-tab-panel"><p className="form-error">{error}</p></section>;
  const { visits, incidents, inventory, requests, documents } = data;
  const open = incidents.filter((item) => !["RESOLVED", "CLOSED"].includes(item.status));
  const low = inventory.filter((item) => item.status === "LOW_STOCK" || item.status === "OUT_OF_STOCK");
  const pending = requests.filter((item) => !["DELIVERED", "REJECTED"].includes(item.status));
  if (tab === "visitas") return <section className="card tower-tab-panel"><div className="section-action"><h2>Visitas</h2>{role === "admin" && <Link className="btn btn--primary" href={`/admin/visitas/nueva?towerId=${tower.id}`}>Programar nueva visita</Link>}</div><div className="tower-record-list">{visits.length ? visits.map((visit) => <article key={visit.id}><div><b>{new Date(`${visit.scheduledDate}T12:00:00`).toLocaleDateString("es-DO")} · {visit.scheduledTime}</b><small>{visit.supervisor} · Progreso {visit.progress}%</small></div><VisitStatusBadge status={visit.status} /><Link href={`/${role}/visitas/${visit.id}`}>Ver visita</Link></article>) : <Empty>No hay visitas registradas para esta torre.</Empty>}</div></section>;
  if (tab === "incidencias") return <section className="card tower-tab-panel"><div className="section-action"><h2>Incidencias</h2><Link className="btn btn--primary" href={`/supervisor/incidencias/nueva?towerId=${tower.id}`}>Nueva incidencia</Link></div><div className="tower-record-list">{incidents.length ? incidents.map((incident) => <article key={incident.id}><div><b>{incident.code} · {incident.title}</b><small>{incident.area} · {new Date(incident.createdAt).toLocaleDateString("es-DO")} · {incident.assignedTo ?? "Sin responsable"}</small></div><IncidentPriorityBadge priority={incident.priority} /><IncidentStatusBadge status={incident.status} /><Link href={`/${role}/incidencias/${incident.id}`}>Ver incidencia</Link></article>) : <Empty>No hay incidencias registradas para esta torre.</Empty>}</div></section>;
  if (tab === "inventario") return <section className="card tower-tab-panel"><div className="section-action"><h2>Inventario</h2><Link className="btn btn--primary" href={`/supervisor/inventario/${tower.id}`}>Revisar inventario</Link></div><div className="tab-mini-kpis"><span><b>{inventory.filter((item) => item.status === "AVAILABLE").length}</b>Disponibles</span><span><b>{inventory.filter((item) => item.status === "LOW_STOCK").length}</b>Bajo stock</span><span><b>{inventory.filter((item) => item.status === "OUT_OF_STOCK").length}</b>Agotados</span></div><div className="tower-record-list">{inventory.length ? inventory.map((item) => <article key={item.id}><div><b>{item.itemName}</b><small>{item.location || "Sin ubicación"} · Revisado {item.lastCheckedAt ? new Date(item.lastCheckedAt).toLocaleDateString("es-DO") : "pendiente"}</small></div><strong>{item.quantity} {item.unit}</strong><InventoryStatusBadge status={item.status} /></article>) : <Empty>No hay inventario registrado para esta torre.</Empty>}</div></section>;
  if (tab === "solicitudes" && role === "admin") return <section className="card tower-tab-panel"><h2>Solicitudes de materiales</h2><div className="tower-record-list">{requests.length ? requests.map((request) => <article key={request.id}><div><b>{request.code}</b><small>{new Date(request.createdAt).toLocaleDateString("es-DO")} · {request.requestedBy} · {request.items.length} productos</small></div><MaterialRequestStatusBadge status={request.status} /><Link href={`/admin/solicitudes/${request.id}`}>Ver solicitud</Link></article>) : <Empty>No hay solicitudes registradas para esta torre.</Empty>}</div></section>;
  if (tab === "fotos") return <section className="card tower-tab-panel"><h2>Galería de fotografías</h2>{photos.length ? <TowerPhotoGallery photos={photos} /> : <Empty>No hay evidencias fotográficas registradas.</Empty>}</section>;
  if (tab === "documentos" && role === "admin") return <section className="card tower-tab-panel"><TowerDocuments documents={documents} /></section>;
  if (tab === "historial" && role === "admin") return <section className="card tower-tab-panel"><h2>Historial completo</h2>{activity.length ? <TowerActivityTimeline items={activity} /> : <Empty>No hay actividad registrada para esta torre.</Empty>}</section>;
  const upcoming = visits.filter((visit) => ["SCHEDULED", "RESCHEDULED"].includes(visit.status)).toSorted((a, b) => `${a.scheduledDate}${a.scheduledTime}`.localeCompare(`${b.scheduledDate}${b.scheduledTime}`))[0];
  const completed = visits.filter((visit) => visit.status === "COMPLETED").toSorted((a, b) => (b.completedAt ?? b.scheduledDate).localeCompare(a.completedAt ?? a.scheduledDate))[0];
  return <><div className="tower-summary-kpis"><article><CalendarDays /><span><small>Próxima visita</small><b>{upcoming ? new Date(`${upcoming.scheduledDate}T12:00:00`).toLocaleDateString("es-DO") : "Pendiente"}</b></span></article><article><CheckCircle2 /><span><small>Última visita</small><b>{completed ? new Date(`${completed.scheduledDate}T12:00:00`).toLocaleDateString("es-DO") : "Sin registro"}</b></span></article><article><ShieldAlert /><span><small>Incidencias abiertas</small><b>{open.length}</b></span></article><article><ShieldAlert /><span><small>Incidencias críticas</small><b>{open.filter((item) => item.priority === "CRITICAL").length}</b></span></article><article><Warehouse /><span><small>Inventario bajo</small><b>{low.length}</b></span></article>{role === "admin" && <article><Building2 /><span><small>Solicitudes pendientes</small><b>{pending.length}</b></span></article>}</div><div className="tower-overview-grid"><div><section className="card tower-info-card"><h2>Información general</h2><dl><div><dt>Tipo</dt><dd>{tower.type}</dd></div><div><dt>Ciudad</dt><dd>{tower.city}</dd></div><div><dt>Pisos</dt><dd>{tower.floors ?? "—"}</dd></div><div><dt>Apartamentos</dt><dd>{tower.apartments ?? "—"}</dd></div><div><dt>Parqueos</dt><dd>{tower.parkingSpaces ?? "—"}</dd></div><div><dt>Año</dt><dd>{tower.yearBuilt ?? "—"}</dd></div></dl><div className="tower-features">{[[tower.hasPool, "Piscina"], [tower.hasGym, "Gimnasio"], [tower.hasSocialArea, "Área social"], [tower.hasGenerator, "Planta"], [tower.hasCameras, "Cámaras"], [tower.hasWaterTank, "Cisterna"]].map(([yes, label]) => <span className={yes ? "yes" : "no"} key={String(label)}>{yes ? "✓" : "—"} {label}</span>)}</div></section><TowerContacts contacts={tower.contacts} /></div><aside><section className="card tower-info-card"><h2><Users /> Supervisores asignados</h2>{tower.supervisors.length ? tower.supervisors.map((supervisor) => <p className="assigned-person" key={supervisor}><i>{supervisor.split(" ").map((part) => part[0]).join("")}</i><b>{supervisor}</b><small>Supervisor activo</small></p>) : <Empty>Sin supervisores asignados.</Empty>}</section><section className="card tower-info-card"><h2>Notas operativas</h2><p>{tower.notes || "Sin notas registradas."}</p></section><section className="card tower-info-card"><h2>Actividad reciente</h2>{activity.length ? <TowerActivityTimeline items={activity.slice(0, 3)} /> : <Empty>No hay actividad reciente.</Empty>}</section></aside></div></>;
}
