"use client";
import type { Tower } from "@/features/towers/types";
import type { TowerAssignment } from "@/features/users/types";
import { Building2, Plus, Search, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

const days = [[1, "Lun"], [2, "Mar"], [3, "Mié"], [4, "Jue"], [5, "Vie"], [6, "Sáb"], [0, "Dom"]] as const;
const dayNames = new Map<number, string>(days);

export function AssignmentManager({ supervisorId }: { supervisorId: string }) {
  const [assignments, setAssignments] = useState<TowerAssignment[]>([]), [towers, setTowers] = useState<Tower[]>([]), [open, setOpen] = useState(false), [query, setQuery] = useState(""), [selected, setSelected] = useState<string[]>([]), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const [startDate, setStartDate] = useState(new Date().toISOString().slice(0, 10)), [workDays, setWorkDays] = useState<number[]>([1, 2, 3, 4, 5]), [shiftStart, setShiftStart] = useState(""), [shiftEnd, setShiftEnd] = useState(""), [notes, setNotes] = useState("");
  const load = useCallback(async () => { setError(""); try { const [assignmentResponse, towerResponse] = await Promise.all([fetch(`/api/admin/assignments?supervisorId=${supervisorId}`, { cache: "no-store" }), fetch("/api/admin/towers", { cache: "no-store" })]); const assignmentData = await assignmentResponse.json() as { assignments?: TowerAssignment[]; error?: string }; const towerData = await towerResponse.json() as { towers?: Tower[]; error?: string }; if (!assignmentResponse.ok || !towerResponse.ok) throw new Error(assignmentData.error ?? towerData.error ?? "No se pudieron cargar las asignaciones."); setAssignments(assignmentData.assignments ?? []); setTowers(towerData.towers ?? []); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "No se pudieron cargar las asignaciones."); } }, [supervisorId]);
  useEffect(() => { void load(); }, [load]);
  const active = assignments.filter((item) => item.status === "ACTIVE");
  const available = useMemo(() => towers.filter((tower) => tower.status !== "INACTIVE" && tower.name.toLowerCase().includes(query.toLowerCase())), [towers, query]);
  const toggleDay = (day: number) => setWorkDays((current) => current.includes(day) ? current.filter((item) => item !== day) : [...current, day]);
  async function save() { setSaving(true); setError(""); try { const response = await fetch("/api/admin/assignments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ supervisorId, towerIds: selected, startDate, workDays, shiftStart, shiftEnd, notes }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "No se pudo guardar la asignación."); setOpen(false); setSelected([]); setNotes(""); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "No se pudo guardar la asignación."); } finally { setSaving(false); } }
  async function end(id: string) { const response = await fetch(`/api/admin/assignments/${id}`, { method: "PATCH" }); const data = await response.json() as { error?: string }; if (!response.ok) { setError(data.error ?? "No se pudo retirar la asignación."); return; } await load(); }

  return <section className="card assignment-panel"><div className="section-action"><div><h2>Torres asignadas</h2><p>{active.length} asignaciones activas</p></div><button type="button" className="btn btn--primary" disabled={!towers.length} onClick={() => setOpen(true)}><Plus /> Asignar torre</button></div>
    {error && <p className="form-error" role="alert">{error}</p>}{!towers.length && <p>Primero registra una torre real para poder asignarla.</p>}
    <div className="assignment-list">{active.map((item) => <article key={item.id}><Building2 /><div><b>{item.towerName ?? item.towerCode}</b><small>Desde {new Date(`${item.startDate}T12:00:00`).toLocaleDateString("es-DO")} · {item.workDays.map((day) => dayNames.get(day)).join(", ")}{item.shiftStart && item.shiftEnd ? ` · ${item.shiftStart}–${item.shiftEnd}` : ""}</small></div><button type="button" onClick={() => void end(item.id)}>Retirar</button></article>)}</div>
    {assignments.some((item) => item.status !== "ACTIVE") && <details><summary>Historial de asignaciones</summary>{assignments.filter((item) => item.status !== "ACTIVE").map((item) => <p key={item.id}>{item.towerName} · Finalizada {item.endDate}</p>)}</details>}
    {open && <div className="assignment-overlay"><section><header><h2>Asignar torres</h2><button type="button" aria-label="Cerrar" onClick={() => setOpen(false)}><X /></button></header><label className="assignment-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar torre..." /></label>
      <div>{available.map((tower) => { const assigned = active.some((item) => item.towerId === tower.id); return <label key={tower.id}><input type="checkbox" disabled={assigned} checked={assigned || selected.includes(tower.id)} onChange={() => setSelected((current) => current.includes(tower.id) ? current.filter((id) => id !== tower.id) : [...current, tower.id])} /><span><b>{tower.name}</b><small>{tower.sector} · {tower.code}</small></span></label>; })}</div>
      <div className="form-grid"><label>Fecha inicial<input type="date" required value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label>Entrada<input type="time" value={shiftStart} onChange={(event) => setShiftStart(event.target.value)} /></label><label>Salida<input type="time" value={shiftEnd} onChange={(event) => setShiftEnd(event.target.value)} /></label><label className="span-2">Días laborales<span className="feature-grid">{days.map(([value, label]) => <span key={value}><input type="checkbox" checked={workDays.includes(value)} onChange={() => toggleDay(value)} /> {label}</span>)}</span></label><label className="span-2">Notas<textarea rows={2} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Turno, acceso o instrucciones especiales" /></label></div>
      <button type="button" className="btn btn--primary" disabled={!selected.length || !workDays.length || saving} onClick={() => void save()}>{saving ? "Guardando…" : "Guardar asignaciones"}</button></section></div>}
  </section>;
}
