"use client";
import type { Incident } from "@/features/incidents/types";
import type { ActivityLog } from "@/features/reports/types";
import type { AppUser } from "@/features/users/types";
import type { Visit } from "@/features/visits/types";
import { ArrowLeft, Building2, CalendarCheck, Edit, Mail, Phone, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AssignmentManager } from "./assignment-manager";
import { UserStatusBadge } from "./user-status-badge";

type Overview={user:AppUser;activeAssignments:number;visits:Visit[];incidents:Incident[];activity:ActivityLog[]};
export function UserProfile({id,supervisor=false}:{id:string;supervisor?:boolean}){const [data,setData]=useState<Overview>(),[error,setError]=useState("");useEffect(()=>{let active=true;fetch(`/api/admin/users/${id}/overview`,{cache:"no-store"}).then(async(response)=>{const result=await response.json() as Overview&{error?:string};if(!response.ok||!result.user)throw new Error(result.error??"No se pudo cargar el usuario.");if(active)setData(result);}).catch((reason)=>{if(active)setError(reason instanceof Error?reason.message:"No se pudo cargar el usuario.");});return()=>{active=false};},[id]);if(error)return <section className="card"><p className="form-error">{error}</p></section>;if(!data)return <section className="card">Cargando expediente del usuario...</section>;const {user,visits,incidents,activity}=data,name=`${user.firstName} ${user.lastName}`;return <><header className="user-profile-head"><Link className="back-link" href={supervisor?"/admin/supervisores":"/admin/usuarios"}><ArrowLeft/> Volver</Link><div><span className="user-avatar large">{user.firstName[0]}{user.lastName[0]}</span><div><h1>{name}</h1><p>{user.jobTitle||"Sin cargo registrado"}</p><span><Mail/>{user.email} {user.phone&&<><Phone/>{user.phone}</>}</span></div><UserStatusBadge status={user.status}/><Link className="btn btn--soft" href={`/admin/usuarios/${id}/editar`}><Edit/> Editar</Link></div></header><div className="profile-kpis"><article><Building2/><b>{data.activeAssignments}</b><span>Torres asignadas</span></article><article><CalendarCheck/><b>{visits.filter((visit)=>visit.status==="COMPLETED").length}</b><span>Visitas realizadas</span></article><article><ShieldAlert/><b>{incidents.length}</b><span>Incidencias reportadas</span></article></div><div className="profile-grid"><div><AssignmentManager supervisorId={id}/><section className="card profile-section"><h2>Agenda y visitas recientes</h2>{visits.length?visits.toSorted((a,b)=>`${b.scheduledDate}${b.scheduledTime}`.localeCompare(`${a.scheduledDate}${a.scheduledTime}`)).slice(0,6).map((visit)=><p key={visit.id}><b>{visit.towerName}</b><span>{new Date(`${visit.scheduledDate}T12:00:00`).toLocaleDateString("es-DO")} · {visit.status}</span></p>):<p>No hay visitas registradas.</p>}</section></div><aside><section className="card profile-section"><h2>Información personal</h2><dl><dt>Rol</dt><dd>{user.role}</dd><dt>Estado</dt><dd>{user.status}</dd><dt>Creado</dt><dd>{new Date(user.createdAt).toLocaleDateString("es-DO")}</dd><dt>Último acceso</dt><dd>{user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString("es-DO"):"Sin acceso"}</dd></dl></section><section className="card profile-section"><h2>Actividad reciente</h2>{activity.length?activity.map((item)=><p key={item.id}><b>{item.description}</b><span>{new Date(item.createdAt).toLocaleString("es-DO")}</span></p>):<p>No hay actividad registrada.</p>}</section></aside></div></>}
