"use client";
import { getUser, listAssignments, listUserActivity } from "@/features/users/service";
import { listVisits } from "@/features/visits/service";
import { listIncidents } from "@/features/incidents/service";
import { ArrowLeft, Building2, CalendarCheck, Edit, Mail, Phone, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { UserStatusBadge } from "./user-status-badge";
import { AssignmentManager } from "./assignment-manager";
export function UserProfile({id,supervisor=false}:{id:string;supervisor?:boolean}){const user=getUser(id),assignments=listAssignments().filter(a=>a.supervisorId===id&&a.status==="ACTIVE"),name=`${user.firstName} ${user.lastName}`,visits=listVisits().filter(v=>v.supervisorId===id),incidents=listIncidents().filter(i=>i.reportedById===id),activity=listUserActivity(id);return <><header className="user-profile-head"><Link className="back-link" href={supervisor?"/admin/supervisores":"/admin/usuarios"}><ArrowLeft/> Volver</Link><div><span className="user-avatar large">{user.firstName[0]}{user.lastName[0]}</span><div><h1>{name}</h1><p>{user.jobTitle}</p><span><Mail/>{user.email} <Phone/>{user.phone}</span></div><UserStatusBadge status={user.status}/><Link className="btn btn--soft" href={`/admin/usuarios/${id}/editar`}><Edit/> Editar</Link></div></header><div className="profile-kpis"><article><Building2/><b>{assignments.length}</b><span>Torres asignadas</span></article><article><CalendarCheck/><b>{visits.filter(v=>v.status==="COMPLETED").length}</b><span>Visitas realizadas</span></article><article><ShieldAlert/><b>{incidents.length}</b><span>Incidencias reportadas</span></article></div><div className="profile-grid"><div><AssignmentManager supervisorId={id}/><section className="card profile-section"><h2>Agenda y visitas recientes</h2>{visits.slice(0,6).map(v=><p key={v.id}><b>{v.towerName}</b><span>{v.scheduledDate} · {v.status}</span></p>)}</section></div><aside><section className="card profile-section"><h2>Información personal</h2><dl><dt>Rol</dt><dd>{user.role}</dd><dt>Estado</dt><dd>{user.status}</dd><dt>Creado</dt><dd>{new Date(user.createdAt).toLocaleDateString("es-DO")}</dd><dt>Último acceso</dt><dd>{user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString("es-DO"):"Sin acceso"}</dd></dl></section><section className="card profile-section"><h2>Actividad reciente</h2>{activity.map(a=><p key={a.id}><b>{a.action}</b><span>{a.actor} · {new Date(a.date).toLocaleDateString("es-DO")}</span></p>)}</section></aside></div></>}
