import type {Tower,TowerStatus} from "./types";
const names=[
 ["tower-tree-iii","TT-003","Tree Tower III","Av. Abraham Lincoln 1108, Santo Domingo","Ensanche Paraíso"],
 ["tower-verde-mare","TVM-004","Torre Verde Mare","Boulevard Zona Hotelera, Cap Cana","Cap Cana"],
 ["tower-villa","VDP-008","Villa del Piantini","Calle Víctor Garrido Puello 18","Piantini"],
 ["tower-one-58","ONE-014","Torre One 58","Calle Rafael Augusto Sánchez 58","Naco"],
 ["tower-monaco","MON-015","Torre Monaco VI","Calle Federico Geraldino 66","Piantini"],
 ["tower-regatta","RGP-016","Regatta Porto","Marina Cap Cana","Cap Cana"],
 ["tower-shalom-v","SHA-018","Shalom V","Calle Max Henríquez Ureña 42","Piantini"],
 ["tower-shalom-vi","SHA-017","Shalom VI","Calle Fantino Falco 31","Naco"],
] as const;
const statuses:TowerStatus[]=["ACTIVE","OBSERVATION","ACTIVE","MAINTENANCE","ACTIVE","ACTIVE","OBSERVATION","INACTIVE"];
export const seedTowers:Tower[]=names.map(([id,code,name,address,sector],i)=>({id,code,name,address,sector,type:i===5?"CONDOMINIUM":"TOWER",city:i===1||i===5?"Punta Cana":"Santo Domingo",province:i===1||i===5?"La Altagracia":"Distrito Nacional",locationReference:"Acceso principal por recepción",floors:10+i,apartments:24+i*4,parkingSpaces:38+i*3,elevators:i%3+1,yearBuilt:2012+i,blocks:i===5?3:1,hasPool:i%2===0,hasGym:i%3!==1,hasSocialArea:true,hasGenerator:true,hasElevators:true,hasCameras:true,hasWaterTank:true,hasPumps:true,status:statuses[i],notes:i===1?"Acceso de supervisores por entrada lateral. Solicitar llave en recepción.":"Coordinar acceso con la administración del condominio.",contacts:[{id:`contact-${i}-1`,type:"Administrador del condominio",name:i%2?"Laura Méndez":"Roberto Castillo",phone:"809-555-01"+String(i).padStart(2,"0"),email:`administracion${i+1}@ejemplo.com`},{id:`contact-${i}-2`,type:"Encargado de mantenimiento",name:"Carlos Pérez",phone:"829-555-02"+String(i).padStart(2,"0"),email:"mantenimiento@ejemplo.com"}],supervisors:i===3?["Ana Gómez"]:["Juan Rodríguez",...(i%3===0?["Carlos Pérez"]:[])],lastVisit:`2026-08-${String(10-(i%4)).padStart(2,"0")}`,nextVisit:`2026-08-${String(12+(i%6)).padStart(2,"0")}`,documents:[{id:`doc-${i}-1`,name:"Reglamento del condominio.pdf",category:"Reglamentos",date:"2026-07-18",uploadedBy:"María Fernández"},{id:`doc-${i}-2`,name:"Reporte mensual julio.pdf",category:"Reportes",date:"2026-08-02",uploadedBy:"Juan Rodríguez"}],photos:[{id:`tp-${i}-1`,url:`mock-photo:tower-${i}`,date:"2026-08-10",origin:"Visita",supervisor:"Juan Rodríguez"},{id:`tp-${i}-2`,url:`mock-photo:incident-${i}`,date:"2026-08-09",origin:"Incidencia",supervisor:"Juan Rodríguez"}],activity:[{id:`act-${i}-1`,date:"2026-08-11T10:00:00",user:"Juan Rodríguez",action:"Visita realizada",entity:"Visita"},{id:`act-${i}-2`,date:"2026-08-10T14:30:00",user:"María Fernández",action:"Información de la torre actualizada",entity:"Torre"},{id:`act-${i}-3`,date:"2026-08-08T09:10:00",user:"María Fernández",action:"Solicitud de materiales aprobada",entity:"Solicitud"}],createdAt:"2026-01-15T09:00:00",updatedAt:"2026-08-10T14:30:00"}));
