"use client";
import { listTowers } from "@/features/towers/service";
import { listAssignments, listUsers } from "@/features/users/service";
import { findConflict } from "@/features/visits/service";
import { listCatalogItems } from "@/features/catalogs/service";
import { listChecklistTemplates } from "@/features/checklists/service";
import type { Visit, VisitInput } from "@/features/visits/types";
import { CalendarPlus } from "lucide-react";
import { useState } from "react";
import { ConflictWarning } from "./conflict-warning";
type Recurrence = NonNullable<Visit["recurrence"]>;
export function VisitForm({visit,initialTowerId,initialSupervisorId,onSubmit}:{visit?:Visit;initialTowerId?:string;initialSupervisorId?:string;onSubmit:(value:VisitInput)=>void}){
  const towers=listTowers(),users=listUsers().filter(u=>(u.role==="SUPERVISOR"||u.role==="INCIDENT_SUPERVISOR")&&u.status==="ACTIVE"),assignments=listAssignments(),types=listCatalogItems("VISIT_TYPE").filter(x=>x.active),templates=listChecklistTemplates().filter(x=>x.active);
  const [towerId,setTowerId]=useState(visit?.towerId??initialTowerId??""); const [supervisorId,setSupervisorId]=useState(visit?.supervisorId??initialSupervisorId??""); const [date,setDate]=useState(visit?.scheduledDate??new Date().toISOString().slice(0,10)); const [time,setTime]=useState(visit?.scheduledTime?.match(/^\d\d:\d\d$/)?visit.scheduledTime:"09:00"); const [duration,setDuration]=useState(visit?.estimatedDuration??90); const [type,setType]=useState(visit?.visitType??types[0]?.label??"Supervisión general"); const [templateId,setTemplateId]=useState(visit?.checklistTemplateId??templates[0]?.id??""); const [notes,setNotes]=useState(visit?.notes??""); const [recurrence,setRecurrence]=useState<Recurrence>(visit?.recurrence??"ONCE");
  const tower=towers.find(t=>t.id===towerId),supervisor=users.find(u=>u.id===supervisorId),template=templates.find(x=>x.id===templateId); const input:VisitInput={towerId,towerName:tower?.name??"",towerCode:tower?.code??"",sector:tower?.sector??"",address:tower?.address??"",supervisorId,supervisor:supervisor?`${supervisor.firstName} ${supervisor.lastName}`:"",scheduledDate:date,scheduledTime:time,estimatedDuration:duration,visitType:type,checklistTemplateId:templateId,checklistTemplateName:template?.name??"",notes,recurrence}; const conflict=towerId&&supervisorId&&date&&time?findConflict(input,visit?.id):undefined;
  return <form className="card visit-admin-form" onSubmit={event=>{event.preventDefault();if(!conflict)onSubmit(input)}}><div className="form-grid"><label>Torre residencial *<select required value={towerId} onChange={e=>setTowerId(e.target.value)}><option value="">Seleccionar torre</option>{towers.map(t=><option key={t.id} value={t.id}>{t.name} · {t.sector}</option>)}</select></label><label>Supervisor *<select required value={supervisorId} onChange={e=>setSupervisorId(e.target.value)}><option value="">Seleccionar supervisor</option>{users.filter(u=>!towerId||assignments.some(a=>a.towerId===towerId&&a.supervisorId===u.id&&a.status==="ACTIVE")).map(u=><option key={u.id} value={u.id}>{u.firstName} {u.lastName}</option>)}</select></label><label>Fecha *<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Hora *<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>Duración estimada<select value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[30,60,90,120].map(value=><option value={value} key={value}>{value} minutos</option>)}</select></label><label>Tipo de visita<select value={type} onChange={e=>setType(e.target.value)}>{types.map(item=><option key={item.id}>{item.label}</option>)}</select></label><label>Checklist<select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templates.map(item=><option value={item.id} key={item.id}>{item.name} · v{item.version}</option>)}</select></label><label>Frecuencia<select value={recurrence} onChange={e=>setRecurrence(e.target.value as Recurrence)}><option value="ONCE">Una sola vez</option><option value="WEEKLY">Semanal</option><option value="BIWEEKLY">Quincenal</option><option value="MONTHLY">Mensual</option></select></label></div><label>Observaciones<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{conflict&&<ConflictWarning visit={conflict}/>}<button className="btn btn--primary" disabled={Boolean(conflict)}><CalendarPlus/>{visit?"Guardar cambios":"Programar visita"}</button></form>;
}
