"use client";
import type {Tower} from "@/features/towers/types";import type {AppUser} from "@/features/users/types";import type {Visit,VisitInput} from "@/features/visits/types";import {CalendarPlus} from "lucide-react";import {useEffect,useState} from "react";
type OptionUser=Pick<AppUser,"id"|"firstName"|"lastName">|{id:string;first_name:string;last_name:string};type Assignment={tower_id:string;supervisor_id:string};type Catalog={id:string;label:string};type Template={id:string;name:string;version:number};
const nameOf=(user:OptionUser)=>"firstName" in user?`${user.firstName} ${user.lastName}`:`${user.first_name} ${user.last_name}`;
export function VisitForm({visit,initialTowerId,initialSupervisorId,onSubmit}:{visit?:Visit;initialTowerId?:string;initialSupervisorId?:string;onSubmit:(value:VisitInput)=>void|Promise<void>}){
 const [towers,setTowers]=useState<Tower[]>([]),[users,setUsers]=useState<OptionUser[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[types,setTypes]=useState<Catalog[]>([]),[templates,setTemplates]=useState<Template[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [towerId,setTowerId]=useState(visit?.towerId??initialTowerId??""),[supervisorId,setSupervisorId]=useState(visit?.supervisorId??initialSupervisorId??""),[date,setDate]=useState(visit?.scheduledDate??new Date().toISOString().slice(0,10)),[time,setTime]=useState(visit?.scheduledTime?.slice(0,5)??"09:00"),[duration,setDuration]=useState(visit?.estimatedDuration??90),[typeId,setTypeId]=useState(visit?.visitTypeId??""),[templateId,setTemplateId]=useState(visit?.checklistTemplateId??""),[notes,setNotes]=useState(visit?.notes??""),[priority,setPriority]=useState<"LOW"|"MEDIUM"|"HIGH">(visit?.priority??"MEDIUM");
 useEffect(()=>{fetch("/api/admin/visits/options",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setTowers(d.towers??[]);setUsers(d.users??[]);setAssignments(d.assignments??[]);setTypes(d.types??[]);setTemplates(d.templates??[]);setTypeId(x=>x||d.types?.[0]?.id||"");setTemplateId(x=>x||d.templates?.[0]?.id||"")}).catch(e=>setError(e instanceof Error?e.message:"No se pudieron cargar las opciones.")).finally(()=>setLoading(false))},[]);
 const tower=towers.find(x=>x.id===towerId),supervisor=users.find(x=>x.id===supervisorId),type=types.find(x=>x.id===typeId),template=templates.find(x=>x.id===templateId),eligible=users.filter(u=>!towerId||assignments.some(a=>a.tower_id===towerId&&a.supervisor_id===u.id));
 const input:VisitInput={towerId,towerName:tower?.name??"",towerCode:tower?.code??"",sector:tower?.sector??"",address:tower?.address??"",supervisorId,supervisor:supervisor?nameOf(supervisor):"",scheduledDate:date,scheduledTime:time,estimatedDuration:duration,visitTypeId:typeId||undefined,visitType:type?.label,checklistTemplateId:templateId||undefined,checklistTemplateName:template?.name,notes,priority,recurrence:"ONCE"};
 if(loading)return <section className="card">Preparando opciones reales…</section>;
 return <form className="card visit-admin-form" onSubmit={async e=>{e.preventDefault();setSaving(true);setError("");try{await onSubmit(input)}catch(err){setError(err instanceof Error?err.message:"No se pudo programar la visita.")}finally{setSaving(false)}}}><div className="form-grid"><label>Torre residencial *<select required value={towerId} onChange={e=>{setTowerId(e.target.value);setSupervisorId("")}}><option value="">Seleccionar torre</option>{towers.filter(t=>t.status!=="INACTIVE").map(t=><option key={t.id} value={t.id}>{t.name} · {t.sector}</option>)}</select></label><label>Supervisor asignado *<select required value={supervisorId} onChange={e=>setSupervisorId(e.target.value)}><option value="">Seleccionar supervisor</option>{eligible.map(u=><option key={u.id} value={u.id}>{nameOf(u)}</option>)}</select></label><label>Fecha *<input type="date" required min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Hora *<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>Duración estimada<select value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[30,60,90,120].map(v=><option value={v} key={v}>{v} minutos</option>)}</select></label><label>Prioridad<select value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}><option value="LOW">Baja</option><option value="MEDIUM">Media</option><option value="HIGH">Alta</option></select></label><label>Tipo de visita<select value={typeId} onChange={e=>setTypeId(e.target.value)}><option value="">Sin clasificar</option>{types.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><label>Checklist<select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Se asignará después</option>{templates.map(x=><option value={x.id} key={x.id}>{x.name} · v{x.version}</option>)}</select></label></div><label>Observaciones<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{!towers.length&&<p className="form-error">Primero debes registrar una torre.</p>}{towerId&&!eligible.length&&<p className="form-error">Esta torre todavía no tiene supervisores asignados.</p>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn btn--primary" disabled={saving||!towerId||!supervisorId}><CalendarPlus/>{saving?"Programando…":visit?"Guardar cambios":"Programar visita"}</button></form>;
}
