import type { Incident } from "./types";
import { seedTowers } from "@/features/towers/mock-data";

const photo=(id:string,type:"BEFORE"|"AFTER"|"GENERAL",seed:string)=>({id,url:`mock-photo:${seed}`,type,createdAt:"2026-08-10T10:35:00"});
export const incidentAreas=["Lobby","Ascensores","Parqueos","Piscina","Gimnasio","Pasillos","Escaleras","Planta eléctrica","Bombas","Cisterna","Fachada","Jardinería","Seguridad","Área social","Administración","Otro"];
export const assignees=[{id:"usr-carlos",name:"Carlos Méndez",type:"INTERNAL",detail:"Mantenimiento"},{id:"usr-luis",name:"Luis Pérez",type:"INTERNAL",detail:"Electricista"},{id:"vendor-abc",name:"Servicios Técnicos ABC",type:"EXTERNAL",detail:"Proveedor"}] as const;
export const towers=seedTowers.map(({id,name,code,sector,address})=>({id,name,code,sector,address}));

export const seedIncidents:Incident[]=[
  {id:"inc-0045",code:"INC-0045",towerId:"tower-verde-mare",towerName:"Torre Verde Mare",towerCode:"TVM-004",address:"Boulevard Zona Hotelera, Cap Cana",sector:"Cap Cana",visitId:"vis-verde-mare",inspectionId:"insp-045",inspectionAnswerId:"answer-elevator",checklistItem:"Ascensor · Funcionamiento",reportedById:"usr-juan",reportedBy:"Juan Rodríguez",assignedToId:"usr-carlos",assignedTo:"Carlos Méndez",assigneeType:"INTERNAL",area:"Ascensores",category:"Equipos",title:"Ascensor de servicio fuera de funcionamiento",description:"El ascensor de servicio no responde desde el nivel de parqueos.",priority:"HIGH",status:"IN_PROGRESS",photos:[photo("ph-45-a","BEFORE","elevator")],createdAt:"2026-08-10T10:35:00",updatedAt:"2026-08-10T15:40:00",updates:[{id:"up-1",userId:"usr-juan",userName:"Juan Rodríguez",userRole:"Supervisor",type:"CREATED",comment:"Incidencia creada desde el checklist de ascensores.",createdAt:"2026-08-10T10:35:00"},{id:"up-2",userId:"usr-admin",userName:"María Fernández",userRole:"Administradora",type:"ASSIGNED",comment:"Incidencia asignada a mantenimiento.",oldStatus:"OPEN",newStatus:"ASSIGNED",createdAt:"2026-08-10T11:10:00"},{id:"up-3",userId:"usr-carlos",userName:"Carlos Méndez",userRole:"Mantenimiento",type:"STATUS_CHANGED",comment:"Diagnóstico y trabajo iniciados.",oldStatus:"ASSIGNED",newStatus:"IN_PROGRESS",createdAt:"2026-08-10T15:40:00"}]},
  {id:"inc-0046",code:"INC-0046",towerId:"tower-villa",towerName:"Villa del Piantini",towerCode:"VDP-008",address:"Calle Víctor Garrido Puello 18",sector:"Piantini",visitId:"vis-villa-piantini",reportedById:"usr-juan",reportedBy:"Juan Rodríguez",assignedToId:"usr-luis",assignedTo:"Luis Pérez",assigneeType:"INTERNAL",area:"Piscina",category:"Plomería",title:"Fuga de agua en cuarto de piscina",description:"Se observa goteo constante próximo a la bomba principal.",priority:"MEDIUM",status:"PENDING_VERIFICATION",photos:[photo("ph-46-a","BEFORE","water"),photo("ph-46-b","AFTER","repair")],createdAt:"2026-08-09T13:15:00",updatedAt:"2026-08-10T09:20:00",updates:[{id:"up-4",userId:"usr-juan",userName:"Juan Rodríguez",userRole:"Supervisor",type:"CREATED",comment:"Fuga detectada durante la visita.",createdAt:"2026-08-09T13:15:00"},{id:"up-5",userId:"usr-luis",userName:"Luis Pérez",userRole:"Electricista",type:"WORK_COMPLETED",comment:"Se reemplazó la unión defectuosa y se realizó prueba de presión.",oldStatus:"IN_PROGRESS",newStatus:"PENDING_VERIFICATION",photos:[photo("ph-46-b","AFTER","repair")],createdAt:"2026-08-10T09:20:00"}]},
  {id:"inc-0047",code:"INC-0047",towerId:"tower-tree-iii",towerName:"Tree Tower III",towerCode:"TT-003",address:"Av. Abraham Lincoln 1108",sector:"Ensanche Paraíso",reportedById:"usr-juan",reportedBy:"Juan Rodríguez",area:"Pasillos",category:"Iluminación",title:"Bombillos apagados en piso 8",description:"Dos luminarias del pasillo principal no encienden.",priority:"LOW",status:"OPEN",photos:[photo("ph-47-a","GENERAL","lights")],createdAt:"2026-08-11T08:40:00",updatedAt:"2026-08-11T08:40:00",updates:[{id:"up-6",userId:"usr-juan",userName:"Juan Rodríguez",userRole:"Supervisor",type:"CREATED",comment:"Incidencia reportada desde el dashboard.",createdAt:"2026-08-11T08:40:00"}]},
  {id:"inc-0048",code:"INC-0048",towerId:"tower-one-58",towerName:"Torre One 58",towerCode:"ONE-014",address:"Calle Rafael Augusto Sánchez 58",sector:"Naco",reportedById:"usr-ana",reportedBy:"Ana Gómez",assignedToId:"vendor-abc",assignedTo:"Servicios Técnicos ABC",assigneeType:"EXTERNAL",area:"Planta eléctrica",category:"Equipos",title:"Vibración anormal en planta eléctrica",description:"La planta presenta vibración y sonido fuera de lo habitual.",priority:"CRITICAL",status:"ASSIGNED",photos:[photo("ph-48-a","BEFORE","generator")],createdAt:"2026-08-10T16:05:00",updatedAt:"2026-08-10T16:40:00",updates:[{id:"up-7",userId:"usr-ana",userName:"Ana Gómez",userRole:"Supervisora",type:"CREATED",comment:"Incidencia crítica reportada.",createdAt:"2026-08-10T16:05:00"},{id:"up-8",userId:"usr-admin",userName:"María Fernández",userRole:"Administradora",type:"ASSIGNED",comment:"Proveedor técnico notificado.",oldStatus:"OPEN",newStatus:"ASSIGNED",createdAt:"2026-08-10T16:40:00"}]},
  {id:"inc-0049",code:"INC-0049",towerId:"tower-monaco",towerName:"Torre Monaco VI",towerCode:"MON-015",address:"Calle Federico Geraldino 66",sector:"Piantini",reportedById:"usr-juan",reportedBy:"Juan Rodríguez",assignedToId:"usr-carlos",assignedTo:"Carlos Méndez",assigneeType:"INTERNAL",area:"Lobby",category:"Mantenimiento físico",title:"Pintura levantada por humedad",description:"Área de pintura deteriorada junto a la puerta de emergencia.",priority:"MEDIUM",status:"RESOLVED",photos:[photo("ph-49-a","BEFORE","paint"),photo("ph-49-b","AFTER","paint-after")],createdAt:"2026-08-06T10:00:00",updatedAt:"2026-08-08T15:00:00",resolvedAt:"2026-08-08T15:00:00",updates:[{id:"up-9",userId:"usr-juan",userName:"Juan Rodríguez",userRole:"Supervisor",type:"CREATED",comment:"Humedad y pintura levantada.",createdAt:"2026-08-06T10:00:00"},{id:"up-10",userId:"usr-admin",userName:"María Fernández",userRole:"Administradora",type:"VERIFIED",comment:"Reparación verificada correctamente.",oldStatus:"PENDING_VERIFICATION",newStatus:"RESOLVED",createdAt:"2026-08-08T15:00:00"}]}
];
