export type AppRole="SUPERVISOR"|"INCIDENT_SUPERVISOR"|"ADMIN";
export type IncidentAction="CREATE"|"COMMENT"|"VIEW_INTERNAL_NOTES"|"ADD_INTERNAL_NOTE"|"ASSIGN"|"CHANGE_PRIORITY"|"CHANGE_STATUS"|"VERIFY"|"CLOSE";
const matrix:Record<AppRole,IncidentAction[]>={SUPERVISOR:["CREATE","COMMENT","VERIFY"],INCIDENT_SUPERVISOR:["CREATE","COMMENT","VERIFY"],ADMIN:["CREATE","COMMENT","VIEW_INTERNAL_NOTES","ADD_INTERNAL_NOTE","ASSIGN","CHANGE_PRIORITY","CHANGE_STATUS","VERIFY","CLOSE"]};
export function can(role:AppRole,action:IncidentAction){return matrix[role].includes(action)}
