"use client";
import { seedIncidents } from "./mock-data";
import type { Incident, IncidentPhoto, IncidentPriority, IncidentStatus, IncidentUpdate, NewIncidentInput } from "./types";
const KEY="adcondo:incidents:v1";
const clone=()=>JSON.parse(JSON.stringify(seedIncidents)) as Incident[];
export function listIncidents(){if(typeof window==="undefined")return clone();const raw=localStorage.getItem(KEY);if(!raw){const initial=clone();localStorage.setItem(KEY,JSON.stringify(initial));return initial}try{return JSON.parse(raw) as Incident[]}catch{return clone()}}
function write(items:Incident[]){localStorage.setItem(KEY,JSON.stringify(items));window.dispatchEvent(new Event("adcondo:incidents"))}
export function getIncident(id:string){return listIncidents().find(item=>item.id===id)??listIncidents()[0]}
export function createIncident(input:NewIncidentInput){const items=listIncidents();const number=Math.max(...items.map(i=>Number(i.code.replace(/\D/g,""))),0)+1;const now=new Date().toISOString();const incident:Incident={...input,id:`inc-${String(number).padStart(4,"0")}`,code:`INC-${String(number).padStart(4,"0")}`,reportedById:"usr-juan",reportedBy:"Juan Rodríguez",status:"OPEN",createdAt:now,updatedAt:now,updates:[{id:crypto.randomUUID(),userId:"usr-juan",userName:"Juan Rodríguez",userRole:"Supervisor",type:"CREATED",comment:"Incidencia reportada.",createdAt:now}]};write([incident,...items]);return incident}
export function addUpdate(id:string,update:Omit<IncidentUpdate,"id"|"createdAt">){const items=listIncidents();const now=new Date().toISOString();let result=items[0];const next=items.map(item=>{if(item.id!==id)return item;result={...item,updatedAt:now,updates:[...item.updates,{...update,id:crypto.randomUUID(),createdAt:now}]};return result});write(next);return result}
export function updateIncident(id:string,patch:Partial<Pick<Incident,"assignedTo"|"assignedToId"|"assigneeType"|"priority"|"status"|"resolvedAt"|"closedAt">>,actor="María Fernández"){const items=listIncidents();const now=new Date().toISOString();let result=items[0];const transitions:Record<IncidentStatus,IncidentStatus[]>={OPEN:["ASSIGNED"],ASSIGNED:["IN_PROGRESS"],IN_PROGRESS:["PENDING_VERIFICATION"],PENDING_VERIFICATION:["RESOLVED","IN_PROGRESS"],RESOLVED:["CLOSED"],CLOSED:[]};const next=items.map(item=>{if(item.id!==id)return item;const allowedStatus=!patch.status||patch.status===item.status||transitions[item.status].includes(patch.status);const safePatch=allowedStatus?patch:{...patch,status:undefined};const comment=safePatch.status&&safePatch.status!==item.status?`Estado cambiado a ${safePatch.status}.`:safePatch.assignedTo?`Incidencia asignada a ${safePatch.assignedTo}.`:safePatch.priority?`Prioridad cambiada a ${safePatch.priority}.`:allowedStatus?"Incidencia actualizada.":"Cambio de estado rechazado por el flujo de resolución.";result={...item,...safePatch,updatedAt:now,updates:[...item.updates,{id:crypto.randomUUID(),userId:"usr-admin",userName:actor,userRole:"Administradora",type:safePatch.assignedTo?"ASSIGNED":"STATUS_CHANGED",comment,oldStatus:item.status,newStatus:safePatch.status,createdAt:now}]};return result});write(next);return result}
export function addSolution(id:string,comment:string,photos:IncidentPhoto[]){const incident=getIncident(id);addUpdate(id,{userId:"usr-carlos",userName:incident.assignedTo??"Mantenimiento",userRole:"Responsable",type:"WORK_COMPLETED",comment,oldStatus:incident.status,newStatus:"PENDING_VERIFICATION",photos});return updateIncident(id,{status:"PENDING_VERIFICATION"},incident.assignedTo??"Mantenimiento")}
export function verifyIncident(id:string,correct:boolean,comment:string){const incident=getIncident(id);const nextStatus:IncidentStatus=correct?"RESOLVED":"IN_PROGRESS";addUpdate(id,{userId:"usr-juan",userName:"Juan Rodríguez",userRole:"Supervisor",type:correct?"VERIFIED":"CORRECTION_REQUIRED",comment:comment||(correct?"Solución verificada correctamente.":"La solución requiere corrección."),oldStatus:incident.status,newStatus:nextStatus});return updateIncident(id,{status:nextStatus,...(correct?{resolvedAt:new Date().toISOString()}:{})},"Juan Rodríguez")}
export const incidentLabels={priority:{LOW:"Baja",MEDIUM:"Media",HIGH:"Alta",CRITICAL:"Crítica"} as Record<IncidentPriority,string>,status:{OPEN:"Abierta",ASSIGNED:"Asignada",IN_PROGRESS:"En proceso",PENDING_VERIFICATION:"Pendiente verificación",RESOLVED:"Resuelta",CLOSED:"Cerrada"} as Record<IncidentStatus,string>};
