"use client";
import type { CatalogItem, CatalogType } from "@/domain/catalogs";
import { Plus, ToggleLeft, ToggleRight } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

const groups: Array<[CatalogType, string]> = [["VISIT_TYPE", "Tipos de visita"], ["INCIDENT_AREA", "Áreas"], ["INCIDENT_CATEGORY", "Categorías de incidencia"], ["PRIORITY", "Prioridades"], ["INVENTORY_CATEGORY", "Categorías de inventario"], ["UNIT", "Unidades"], ["DOCUMENT_CATEGORY", "Categorías de documentos"]];
const codeFor = (label: string) => label.trim().toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\W+/g, "_").replace(/^_|_$/g, "");

export function CatalogAdmin() {
  const [items, setItems] = useState<CatalogItem[]>([]), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/admin/catalogs", { cache: "no-store" }); const data = await response.json() as { items?: CatalogItem[]; error?: string }; if (!response.ok || !data.items) throw new Error(data.error ?? "No se pudieron cargar los catálogos."); setItems(data.items); }, []);
  useEffect(() => { load().catch((reason) => setError(reason instanceof Error ? reason.message : "No se pudieron cargar los catálogos.")); }, [load]);
  async function add(type: CatalogType) { const label = prompt("Nombre del valor"); if (!label?.trim()) return; setBusy(true); setError(""); try { const response = await fetch("/api/admin/catalogs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type, code: codeFor(label), label: label.trim() }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "No se pudo crear el valor."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo crear el valor."); } finally { setBusy(false); } }
  async function update(item: CatalogItem, changes: { label?: string; active?: boolean }) { setBusy(true); setError(""); try { const response = await fetch(`/api/admin/catalogs/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(changes) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "No se pudo actualizar el valor."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo actualizar el valor."); } finally { setBusy(false); } }
  return <div><div className="dashboard-heading"><div><span className="mobile-overline">Administración</span><h1>Configuración y catálogos</h1><p>Valores centrales reutilizados por visitas, incidencias, inventario y documentos.</p></div></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="catalog-grid">{groups.map(([type, title]) => <section className="panel" key={type}><div className="panel__head"><h2>{title}</h2><button className="icon-action" disabled={busy} onClick={() => add(type)} aria-label={`Agregar a ${title}`}><Plus /></button></div><div className="catalog-list">{items.filter((item) => item.type === type).toSorted((a, b) => a.order - b.order).map((item) => <div key={item.id} className={!item.active ? "inactive" : ""}><button className="item-copy" disabled={busy} onClick={() => { const label = prompt("Editar valor", item.label); if (label?.trim()) void update(item, { label: label.trim() }); }}><strong>{item.label}</strong><small>{item.code}</small></button><button className="icon-action" disabled={busy} onClick={() => update(item, { active: !item.active })} aria-label={item.active ? "Desactivar" : "Activar"}>{item.active ? <ToggleRight /> : <ToggleLeft />}</button></div>)}{!items.some((item) => item.type === type) && <p>No hay valores registrados.</p>}</div></section>)}</div></div>;
}
