"use client";
import type { ChecklistItem, ChecklistTemplateAggregate } from "@/domain/checklists";
import { seedChecklistTemplates } from "@/data/mock/checklists";
const KEY = "adcondo:checklist-templates:v1";
const read = (): ChecklistTemplateAggregate[] => { const seed = structuredClone(seedChecklistTemplates); if (typeof window === "undefined") return seed; const raw = localStorage.getItem(KEY); if (!raw) { localStorage.setItem(KEY, JSON.stringify(seed)); return seed; } try { return JSON.parse(raw); } catch { return seed; } };
const write = (items: ChecklistTemplateAggregate[]) => localStorage.setItem(KEY, JSON.stringify(items));
export const listChecklistTemplates = read;
export function createChecklistTemplate(name: string, description?: string) { const now = new Date().toISOString(); const template: ChecklistTemplateAggregate = { id: crypto.randomUUID(), name, description, active: true, version: 1, createdAt: now, updatedAt: now, sections: [] }; write([template, ...read()]); return template; }
export function addChecklistSection(templateId: string, name: string) { write(read().map(template => template.id === templateId ? { ...template, updatedAt: new Date().toISOString(), sections: [...template.sections, { id: crypto.randomUUID(), templateId, name, active: true, order: template.sections.length, items: [] }] } : template)); }
export function addChecklistItem(templateId: string, sectionId: string, input: Pick<ChecklistItem,"name"|"description"|"required">) { write(read().map(template => template.id === templateId ? { ...template, updatedAt: new Date().toISOString(), sections: template.sections.map(section => section.id === sectionId ? { ...section, items: [...section.items, { ...input, id: crypto.randomUUID(), sectionId, active: true, order: section.items.length }] } : section) } : template)); }
export function updateChecklistItem(templateId: string, sectionId: string, itemId: string, patch: Partial<ChecklistItem>) { write(read().map(template => template.id === templateId ? { ...template, updatedAt: new Date().toISOString(), sections: template.sections.map(section => section.id === sectionId ? { ...section, items: section.items.map(item => item.id === itemId ? { ...item, ...patch, id: item.id, sectionId: item.sectionId } : item) } : section) } : template)); }
export function moveChecklistItem(templateId: string, sectionId: string, itemId: string, direction: -1|1) { const templates = read(); const template = templates.find(x => x.id === templateId); const section = template?.sections.find(x => x.id === sectionId); if (!section) return; const index = section.items.findIndex(x => x.id === itemId), target = index + direction; if (index < 0 || target < 0 || target >= section.items.length) return; [section.items[index], section.items[target]] = [section.items[target], section.items[index]]; section.items.forEach((item, order) => item.order = order); template!.updatedAt = new Date().toISOString(); write(templates); }
