import type { ChecklistSectionData, Visit } from "./types";

export const visits: Visit[] = [
  { id:"vis-tree-iii", towerName:"Tree Tower III", towerCode:"TT-003", sector:"Ensanche Paraíso", address:"Av. Abraham Lincoln 1108, Santo Domingo", scheduledDate:"2026-08-11", scheduledTime:"09:00 AM", status:"COMPLETED", supervisor:"Juan Rodríguez", progress:100, startedAt:"2026-08-11T09:03:00", completedAt:"2026-08-11T10:17:00" },
  { id:"vis-verde-mare", towerName:"Torre Verde Mare", towerCode:"TVM-004", sector:"Cap Cana", address:"Boulevard Zona Hotelera, Cap Cana", scheduledDate:"2026-08-11", scheduledTime:"11:00 AM", status:"IN_PROGRESS", supervisor:"Juan Rodríguez", progress:36, startedAt:"2026-08-11T10:32:00" },
  { id:"vis-villa-piantini", towerName:"Villa del Piantini", towerCode:"VDP-008", sector:"Piantini", address:"Calle Víctor Garrido Puello 18", scheduledDate:"2026-08-11", scheduledTime:"01:00 PM", status:"SCHEDULED", supervisor:"Juan Rodríguez", progress:0 },
  { id:"vis-one-58", towerName:"Torre One 58", towerCode:"ONE-014", sector:"Naco", address:"Calle Rafael Augusto Sánchez 58", scheduledDate:"2026-08-11", scheduledTime:"04:00 PM", status:"SCHEDULED", supervisor:"Juan Rodríguez", progress:0 },
  { id:"vis-monaco-vi", towerName:"Torre Monaco VI", towerCode:"MON-015", sector:"Piantini", address:"Calle Federico Geraldino 66", scheduledDate:"2026-08-12", scheduledTime:"09:30 AM", status:"SCHEDULED", supervisor:"Juan Rodríguez", progress:0 },
  { id:"vis-regatta", towerName:"Regatta Porto", towerCode:"RGP-016", sector:"Cap Cana", address:"Marina Cap Cana", scheduledDate:"2026-08-13", scheduledTime:"10:00 AM", status:"RESCHEDULED", supervisor:"Juan Rodríguez", progress:0, rescheduledTo:"14 de agosto, 10:00 AM" },
  { id:"vis-shalom-v", towerName:"Shalom V", towerCode:"SHA-018", sector:"Piantini", address:"Calle Max Henríquez Ureña 42", scheduledDate:"2026-08-08", scheduledTime:"02:00 PM", status:"COMPLETED", supervisor:"Juan Rodríguez", progress:100 },
  { id:"vis-shalom-vi", towerName:"Shalom VI", towerCode:"SHA-017", sector:"Naco", address:"Calle Fantino Falco 31", scheduledDate:"2026-08-15", scheduledTime:"03:00 PM", status:"CANCELLED", supervisor:"Juan Rodríguez", progress:0 },
];

const item = (id:string,title:string,instructions:string): {id:string;title:string;instructions:string;required:true} => ({id,title,instructions,required:true});

export const checklistSections: ChecklistSectionData[] = [
  { id:"security", title:"Seguridad y acceso", items:[item("guard-post","Garita / seguridad","Personal, uniforme, registro de visitantes, llaves y libro de novedades."),item("main-entry","Entrada principal","Puertas, cristales, cerraduras, iluminación y control de acceso."),item("access-cameras","Cámaras de acceso","Funcionamiento, ángulos, limpieza y grabación."),item("gates","Portones y barreras","Apertura, controles, motores y seguridad.")]},
  { id:"parking", title:"Parqueos", items:[item("parking-clean","Limpieza general","Basura, manchas, filtraciones y objetos fuera de lugar."),item("parking-light","Iluminación","Bombillos, sensores y zonas oscuras."),item("parking-lines","Señalización","Líneas, rampas, numeración y rutas despejadas."),item("parking-drains","Drenajes","Rejillas limpias, sin charcos ni obstrucciones.")]},
  { id:"hygiene", title:"Higiene y basura", items:[item("bathrooms","Baños comunes","Jabón, papel, lavamanos, espejos, inodoros, olor y piso seco."),item("bins","Zafacones por áreas","Fundas, tapas, limpieza, ubicación y ausencia de rebose."),item("trash-room","Cuarto de basura","Tanques, ventilación, desinfección, olores y plagas."),item("cleaning-materials","Materiales de limpieza","Verificar existencia real y fotografiar su ubicación.")]},
  { id:"common", title:"Lobby, pasillos y escaleras", items:[item("lobby","Lobby","Piso, cristales, muebles, olor, aire, luces, paredes y recepción."),item("hallways","Pasillos por piso","Pisos, pintura, luces, extintores, humedad y puertas de emergencia."),item("stairs","Escaleras","Escalones, pasamanos, pintura, iluminación y rutas libres.")]},
  { id:"elevators", title:"Ascensores", items:[item("elevator-operation","Funcionamiento","Nivelación, ruidos, puertas y certificado de mantenimiento."),item("elevator-clean","Limpieza interior","Piso, acero, cristal, espejo y olor."),item("elevator-controls","Botoneras e iluminación","Botones, indicadores, luces y ventilación.")]},
  { id:"social", title:"Áreas sociales / piscina / gimnasio", items:[item("social-room","Salón social","Muebles, baños, luces, ventilación y entrega después de uso."),item("pool","Piscina / jacuzzi","Agua, cloro/pH, bomba, filtro, drenajes, bordes y normas."),item("terrace","Terraza / BBQ","Piso, barandas, parrilla, gas, muebles y drenajes."),item("gym","Gimnasio","Máquinas, cables, pesas, espejos, ventilación y piezas rotas.")]},
  { id:"physical", title:"Mantenimiento físico", items:[item("paint","Pintura y paredes","Manchas, golpes, humedad, moho, grietas y retoques."),item("floors-roofs","Pisos y techos","Piezas rotas, plafones, filtraciones y áreas resbalosas."),item("lighting","Iluminación","Bombillos, emergencias, sensores y zonas oscuras."),item("hardware","Puertas y herrajes","Cerraduras, bisagras, manubrios, cierrapuertas y barras antipánico.")]},
  { id:"systems", title:"Equipos y sistemas", items:[item("generator","Planta eléctrica","Combustible, arranque, fugas, baterías, limpieza y bitácora."),item("pumps","Bombas / sistema de agua","Presión, fugas, ruidos, cisterna, tinacos y mantenimiento."),item("cctv","Cámaras / DVR","Grabación, fecha/hora, respaldo, lentes y tarjetas de acceso."),item("electric","Sistema eléctrico común","Paneles, breakers, tomas, cables y cuarto eléctrico.")]},
  { id:"staff", title:"Personal", items:[item("staff-look","Presentación","Uniforme, higiene, carnet, calzado y apariencia profesional."),item("staff-shifts","Puntualidad y turnos","Llegada, firma, relevo, permanencia y novedades."),item("staff-service","Actitud y servicio","Trato, lenguaje, celular, disposición y manejo de quejas.")]},
  { id:"exterior", title:"Jardinería, fachada y administración", items:[item("gardens","Jardinería","Poda, riego, hojas secas, maceteros y áreas verdes."),item("facade","Fachada y perímetro","Pintura, cristales, acera, luces, portones y drenajes."),item("admin-followup","Administración y seguimiento","Novedades, quejas, responsables, fechas, proveedores y facturas.")]},
];

export const totalChecklistItems = checklistSections.reduce((sum, section) => sum + section.items.length, 0);

export function getVisit(id: string) { return visits.find((visit) => visit.id === id) ?? visits[2]; }
