"use client";import {visits as seeds} from "./mock-data";import type {Visit,VisitActivity,VisitInput,VisitScheduleHistory,VisitStatus} from "./types";
const VK="adcondo:visits:v2",HK="adcondo:visit-history:v1",AK="adcondo:visit-activity:v1",NK="adcondo:notifications:v1";const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));const enriched=seeds.map((v,i)=>({...v,code:`VIS-${String(i+1).padStart(4,"0")}`,towerId:{"TT-003":"tower-tree-iii","TVM-004":"tower-verde-mare","VDP-008":"tower-villa","ONE-014":"tower-one-58","MON-015":"tower-monaco","RGP-016":"tower-regatta","SHA-018":"tower-shalom-v","SHA-017":"tower-shalom-vi"}[v.towerCode],supervisorId:v.supervisor==="Juan Rodríguez"?"usr-juan":"usr-maria",estimatedDuration:90,visitType:"Supervisión rutinaria",checklistTemplateId:"checklist-general",checklistTemplateName:"Checklist general de supervisión",createdById:"usr-admin"}));
const read=<T,>(k:string,seed:T):T=>{if(typeof window==="undefined")return clone(seed);const x=localStorage.getItem(k);if(!x){localStorage.setItem(k,JSON.stringify(seed));return clone(seed)}try{return JSON.parse(x)}catch{return clone(seed)}};const write=(k:string,v:unknown)=>localStorage.setItem(k,JSON.stringify(v));export const listVisits=()=>read<Visit[]>(VK,enriched);export const getVisitRecord=(id:string)=>listVisits().find(v=>v.id===id)??listVisits()[0];export const visitHistory=(id:string)=>read<VisitScheduleHistory[]>(HK,[]).filter(h=>h.visitId===id);export const visitActivity=(id:string)=>read<VisitActivity[]>(AK,[]).filter(a=>a.visitId===id);
const audit=(visitId:string,action:string,detail?:string)=>write(AK,[{id:crypto.randomUUID(),visitId,action,user:"Laura Méndez",createdAt:new Date().toISOString(),detail},...read<VisitActivity[]>(AK,[])]);const notify=(text:string)=>write(NK,[{id:crypto.randomUUID(),text,createdAt:new Date().toISOString()},...read<unknown[]>(NK,[])]);
export function findConflict(input:VisitInput,excludeId?:string){const start=new Date(`${input.scheduledDate}T${input.scheduledTime}`),end=new Date(start.getTime()+(input.estimatedDuration??60)*60000);return listVisits().find(v=>v.id!==excludeId&&v.supervisorId===input.supervisorId&&!['CANCELLED','COMPLETED'].includes(v.status)&&v.scheduledDate===input.scheduledDate&&(()=>{const s=new Date(`${v.scheduledDate}T${v.scheduledTime}`),e=new Date(s.getTime()+(v.estimatedDuration??60)*60000);return start<e&&end>s})())}
export function createVisit(input:VisitInput){const all=listVisits(),n=Math.max(...all.map(v=>Number((v.code??'').replace(/\D/g,''))),0)+1,v:Visit={...input,id:`visit-${crypto.randomUUID()}`,code:`VIS-${String(n).padStart(4,'0')}`,status:'SCHEDULED',progress:0,createdById:'usr-admin'};write(VK,[v,...all]);audit(v.id,'Visita creada');notify(`Nueva visita programada en ${v.towerName} a las ${v.scheduledTime}.`);return v}
export function updateVisit(id:string,input:VisitInput){let result=getVisitRecord(id);write(VK,listVisits().map(v=>v.id===id?(result={...v,...input}):v));audit(id,'Visita editada');return result}
export function rescheduleVisit(id:string,date:string,time:string,reason:string){const old=getVisitRecord(id),now=new Date().toISOString(),h:VisitScheduleHistory={id:crypto.randomUUID(),visitId:id,previousDate:old.scheduledDate,previousTime:old.scheduledTime,newDate:date,newTime:time,reason,changedById:'usr-admin',changedBy:'Laura Méndez',createdAt:now};write(HK,[h,...read<VisitScheduleHistory[]>(HK,[])]);write(VK,listVisits().map(v=>v.id===id?{...v,scheduledDate:date,scheduledTime:time,status:'RESCHEDULED' as VisitStatus,rescheduledTo:`${date} ${time}`}:v));audit(id,'Visita reprogramada',reason);notify(`Tu visita a ${old.towerName} fue reprogramada para las ${time}.`)}
export function cancelVisit(id:string,reason:string){const old=getVisitRecord(id);write(VK,listVisits().map(v=>v.id===id?{...v,status:'CANCELLED' as VisitStatus,cancelledAt:new Date().toISOString(),cancellationReason:reason}:v));audit(id,'Visita cancelada',reason);notify(`Tu visita a ${old.towerName} fue cancelada.`)}
