import { requireAdmin } from "@/lib/auth/require-admin";
import { supabaseServerFetch } from "@/lib/database/verified-request";
import { z } from "zod";

export const runtime = "nodejs";
type Context = { params: Promise<{ itemId: string }> };
const schema = z.object({ name:z.string().trim().min(2).max(200).optional(), description:z.string().trim().max(1000).optional(), required:z.boolean().optional(), active:z.boolean().optional(), direction:z.union([z.literal(-1),z.literal(1)]).optional() }).refine((value)=>Object.keys(value).length>0);
type ItemRow={id:string;section_id:string;sort_order:number};

async function move(item:ItemRow,direction:-1|1){const comparison=direction<0?"lt":"gt",order=direction<0?"desc":"asc",response=await supabaseServerFetch(`checklist_items?select=id,section_id,sort_order&section_id=eq.${item.section_id}&sort_order=${comparison}.${item.sort_order}&order=sort_order.${order}&limit=1`),[target]=response.ok?await response.json() as ItemRow[]:[];if(!target)return;const temporary=-1000000-Math.abs(item.sort_order);const first=await supabaseServerFetch(`checklist_items?id=eq.${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({sort_order:temporary})});if(!first.ok)throw new Error("No se pudo reordenar.");const second=await supabaseServerFetch(`checklist_items?id=eq.${target.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({sort_order:item.sort_order})});if(!second.ok){await supabaseServerFetch(`checklist_items?id=eq.${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({sort_order:item.sort_order})});throw new Error("No se pudo reordenar.");}const third=await supabaseServerFetch(`checklist_items?id=eq.${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({sort_order:target.sort_order})});if(!third.ok)throw new Error("No se pudo completar el orden.");}

export async function PATCH(request:Request,{params}:Context){const actor=await requireAdmin();if(!actor)return Response.json({error:"No autorizado."},{status:403});try{const {itemId}=await params,input=schema.parse(await request.json()),currentResponse=await supabaseServerFetch(`checklist_items?select=id,section_id,sort_order&id=eq.${itemId}&limit=1`),[current]=currentResponse.ok?await currentResponse.json() as ItemRow[]:[];if(!current)return Response.json({error:"Elemento no encontrado."},{status:404});if(input.direction)await move(current,input.direction);const body:Record<string,unknown>={};if(input.name!==undefined)body.name=input.name;if(input.description!==undefined)body.description=input.description||null;if(input.required!==undefined)body.required=input.required;if(input.active!==undefined)body.active=input.active;if(Object.keys(body).length){const response=await supabaseServerFetch(`checklist_items?id=eq.${itemId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!response.ok)return Response.json({error:"No se pudo actualizar el elemento."},{status:502});}await supabaseServerFetch("activity_logs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actor_user_id:actor.id,action:"CHECKLIST_ITEM_UPDATED",entity_type:"checklist_item",entity_id:itemId,metadata:{...body,direction:input.direction}})});return Response.json({ok:true});}catch(error){if(error instanceof z.ZodError)return Response.json({error:"El cambio no es válido."},{status:400});return Response.json({error:"No se pudo actualizar el elemento."},{status:500});}}
