"use client";
import { getAdminDashboardData } from "@/features/dashboard/service";
import { IconBox, Status } from "@/components/ui";
import { AlertOctagon, AlertTriangle, Building2, CalendarCheck2, CalendarClock, CheckCircle2, ShoppingCart, UsersRound } from "lucide-react";
import Link from "next/link";
import { Cell, Pie, PieChart, ResponsiveContainer } from "recharts";
const statusNames={COMPLETED:"Completadas",IN_PROGRESS:"En progreso",SCHEDULED:"Pendientes",RESCHEDULED:"Reprogramadas",CANCELLED:"Canceladas"};
const colors={COMPLETED:"#19a765",IN_PROGRESS:"#f59e0b",SCHEDULED:"#1769f6",RESCHEDULED:"#8b5cf6",CANCELLED:"#94a3b8"};
export default function AdminDashboard(){const data=getAdminDashboardData();const m=data.metrics;const states=Object.entries(statusNames).map(([key,name])=>({name,value:data.visits.filter(x=>x.status===key).length,color:colors[key as keyof typeof colors]})).filter(x=>x.value);const kpis=[[Building2,"Total de torres",m.totalTowers,"blue","/admin/torres"],[UsersRound,"Supervisores activos",m.activeSupervisors,"green","/admin/supervisores"],[CalendarCheck2,"Visitas de hoy",m.visitsToday,"purple","/admin/visitas"],[CheckCircle2,"Completadas",m.completedVisits,"green","/admin/visitas"],[CalendarClock,"Pendientes",m.pendingVisits,"orange","/admin/calendario"],[AlertTriangle,"Incidencias abiertas",m.openIncidents,"red","/admin/incidencias"],[AlertOctagon,"Críticas",m.criticalIncidents,"red","/admin/incidencias"],[ShoppingCart,"Solicitudes pendientes",m.pendingRequests,"orange","/admin/solicitudes"]] as const;return <><div className="dashboard-heading"><div><span className="mobile-overline">Vista general</span><h1>Panel administrativo</h1><p>Métricas calculadas desde la fuente local central.</p></div><span className="date-pill"><CalendarCheck2 size={17}/>{new Intl.DateTimeFormat("es-DO",{dateStyle:"long"}).format(new Date())}</span></div><section className="kpi-grid kpi-grid--admin">{kpis.map(([Icon,label,value,tone,href])=><Link className="kpi-link" href={href} key={label}><article><IconBox icon={Icon} tone={tone}/><div><span>{label}</span><strong>{value}</strong></div></article></Link>)}</section><div className="admin-chart-grid"><section className="panel chart-panel"><div className="panel__head"><div><span className="panel-kicker">Distribución real</span><h2>Visitas por estado</h2></div><Link href="/admin/reportes">Ver reportes</Link></div><div className="pie-layout"><div className="pie-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={states} dataKey="value" innerRadius={52} outerRadius={72} paddingAngle={3}>{states.map(s=><Cell key={s.name} fill={s.color}/>)}</Pie></PieChart></ResponsiveContainer><span><strong>{data.visits.length}</strong><small>Visitas</small></span></div><div className="legend">{states.map(s=><span key={s.name}><i style={{background:s.color}}/>{s.name}<b>{s.value}</b></span>)}</div></div></section><section className="panel"><div className="panel__head"><div><span className="panel-kicker">Atención requerida</span><h2>Incidencias recientes</h2></div><Link href="/admin/incidencias">Ver todas</Link></div><div className="admin-table">{data.incidents.slice(0,4).map(x=><div key={x.id}><Status tone={x.priority==="CRITICAL"?"red":"orange"}>{x.priority}</Status><span><strong>{x.towerName}</strong><small>{x.title}</small></span><b>{x.status}</b><time>{new Date(x.updatedAt).toLocaleDateString("es-DO")}</time></div>)}</div></section></div></>}
