"use client";import {seedAssignments,seedUserActivity,seedUsers} from "./mock-data";import type {AppRole,AppUser,UserActivity,UserInput} from "./types";
const UK="adcondo:users:v1",AK="adcondo:assignments:v1",CK="adcondo:current-role:v1",LK="adcondo:user-activity:v1";const read=<T,>(k:string,seed:T):T=>{if(typeof window==="undefined")return structuredClone(seed);const raw=localStorage.getItem(k);if(!raw){localStorage.setItem(k,JSON.stringify(seed));return structuredClone(seed)}try{return JSON.parse(raw)}catch{return structuredClone(seed)}};const write=(k:string,v:unknown)=>localStorage.setItem(k,JSON.stringify(v));
export const listUsers=()=>read(UK,seedUsers);export const getUser=(id:string)=>listUsers().find(u=>u.id===id)??listUsers()[0];export const listAssignments=()=>read(AK,seedAssignments);export const listUserActivity=(id?:string)=>read(LK,seedUserActivity).filter(a=>!id||a.userId===id);
const log=(userId:string,action:string)=>write(LK,[{id:crypto.randomUUID(),userId,actor:"Laura Méndez",action,date:new Date().toISOString()},...read<UserActivity[]>(LK,seedUserActivity)]);
export function createUser(input:UserInput){const now=new Date().toISOString(),u:AppUser={...input,id:`usr-${crypto.randomUUID()}`,createdAt:now,updatedAt:now};write(UK,[u,...listUsers()]);log(u.id,"Usuario creado");return u}export function updateUser(id:string,input:UserInput){let result=getUser(id);write(UK,listUsers().map(u=>u.id===id?(result={...u,...input,id:u.id,updatedAt:new Date().toISOString()}):u));log(id,"Usuario editado");return result}
export function assignTowers(supervisorId:string,towerIds:string[]){const now=new Date().toISOString(),all=listAssignments();const additions=towerIds.filter(t=>!all.some(a=>a.towerId===t&&a.supervisorId===supervisorId&&a.status==="ACTIVE")).map(towerId=>({id:crypto.randomUUID(),towerId,supervisorId,assignedById:"usr-admin",assignedBy:"Laura Méndez",status:"ACTIVE" as const,startDate:now.slice(0,10),createdAt:now,updatedAt:now}));write(AK,[...additions,...all]);log(supervisorId,`${additions.length} torre(s) asignada(s)`)}
export function endAssignment(id:string){const now=new Date().toISOString(),all=listAssignments(),a=all.find(x=>x.id===id);write(AK,all.map(x=>x.id===id?{...x,status:"ENDED",endDate:now.slice(0,10),endedBy:"Laura Méndez",updatedAt:now}:x));if(a)log(a.supervisorId,"Supervisor retirado de torre")}
export function currentUser(role?:AppRole){const r=role??(typeof window!=="undefined"?(localStorage.getItem(CK) as AppRole):"SUPERVISOR")??"SUPERVISOR";return r==="ADMIN"?getUser("usr-admin"):getUser("usr-juan")}export function setCurrentRole(role:AppRole){localStorage.setItem(CK,role)}
export const userStatusLabels={ACTIVE:"Activo",INACTIVE:"Inactivo",SUSPENDED:"Suspendido",PENDING:"Pendiente"};
