"use client";
import { IncidentPhotoUploader } from "@/components/incidents/photo-uploader";
import type { IncidentPhoto, IncidentPriority } from "@/features/incidents/types";
import type { Tower } from "@/features/towers/types";
import { AlertTriangle, ArrowLeft, Building2, CheckCircle2, Send } from "lucide-react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";

type Catalog={id:string;catalog_type:string;code:string;label:string};
export default function NewIncidentPage(){
  const params=useSearchParams(),router=useRouter();
  const [towers,setTowers]=useState<Tower[]>([]),[catalogs,setCatalogs]=useState<Catalog[]>([]),[towerId,setTowerId]=useState(params.get("towerId")??""),[areaId,setAreaId]=useState(""),[categoryId,setCategoryId]=useState(""),[title,setTitle]=useState(params.get("title")??""),[description,setDescription]=useState(""),[priority,setPriority]=useState<IncidentPriority>((params.get("priority") as IncidentPriority)||"MEDIUM"),[observation,setObservation]=useState(""),[photos,setPhotos]=useState<IncidentPhoto[]>([]),[submitted,setSubmitted]=useState(false),[error,setError]=useState("");
  useEffect(()=>{fetch("/api/incidents/options",{cache:"no-store"}).then(async response=>{const data=await response.json() as {towers?:Tower[];catalogs?:Catalog[];error?:string};if(!response.ok)throw new Error(data.error);const available=data.towers??[];setTowers(available);setCatalogs(data.catalogs??[]);setTowerId(current=>current||available[0]?.id||"");const areas=(data.catalogs??[]).filter(item=>item.catalog_type==="INCIDENT_AREA");const categories=(data.catalogs??[]).filter(item=>item.catalog_type==="INCIDENT_CATEGORY");setAreaId(current=>current||areas[0]?.id||"");setCategoryId(current=>current||categories[0]?.id||"")}).catch(reason=>setError(reason instanceof Error?reason.message:"No se pudieron cargar las opciones."))},[]);
  const areas=catalogs.filter(item=>item.catalog_type==="INCIDENT_AREA"),categories=catalogs.filter(item=>item.catalog_type==="INCIDENT_CATEGORY");
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setSubmitted(true);setError("");const form=new FormData();form.set("towerId",towerId);form.set("areaId",areaId);form.set("categoryId",categoryId);form.set("title",title);form.set("description",description);form.set("priority",priority);form.set("observation",observation);if(params.get("visitId"))form.set("visitId",params.get("visitId")!);if(params.get("answerId"))form.set("itemId",params.get("answerId")!);photos.forEach(photo=>{if(photo.file)form.append("photos",photo.file)});const response=await fetch("/api/incidents",{method:"POST",body:form});const data=await response.json() as {incidentId?:string;error?:string};if(!response.ok||!data.incidentId){setError(data.error??"No se pudo registrar la incidencia.");setSubmitted(false);return}router.push(`/supervisor/incidencias/${data.incidentId}`);router.refresh()};
  return <div className="new-incident-page"><Link className="back-link" href="/supervisor/incidencias"><ArrowLeft/>Volver a incidencias</Link><header><span className="new-incident-icon"><AlertTriangle/></span><div><h1>Nueva incidencia</h1><p>Documenta el hallazgo para iniciar su seguimiento.</p></div><span className="initial-status">Estado inicial: <b>Abierta</b></span></header><form onSubmit={event=>void submit(event)}><section className="incident-form-card"><h2><Building2/>Ubicación del hallazgo</h2><div className="incident-form-grid"><label>Torre<select value={towerId} onChange={event=>setTowerId(event.target.value)} required><option value="">Seleccionar torre</option>{towers.map(tower=><option value={tower.id} key={tower.id}>{tower.name} · {tower.code}</option>)}</select></label><label>Área<select value={areaId} onChange={event=>setAreaId(event.target.value)} required>{areas.map(area=><option value={area.id} key={area.id}>{area.label}</option>)}</select></label><label>Categoría<select value={categoryId} onChange={event=>setCategoryId(event.target.value)} required>{categories.map(category=><option value={category.id} key={category.id}>{category.label}</option>)}</select></label></div></section><section className="incident-form-card"><h2><AlertTriangle/>Descripción del problema</h2><label>Título<input value={title} onChange={event=>setTitle(event.target.value)} placeholder="Resumen breve del problema" required/></label><label>Descripción<textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="Describe qué encontraste y cómo afecta la operación..." required/></label><div className="incident-form-grid"><label>Prioridad<select value={priority} onChange={event=>setPriority(event.target.value as IncidentPriority)}><option value="LOW">Baja</option><option value="MEDIUM">Media</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></select></label><label>Observación adicional<input value={observation} onChange={event=>setObservation(event.target.value)} placeholder="Opcional"/></label></div></section><section className="incident-form-card"><h2>Evidencias fotográficas</h2><p>Agrega hasta 8 fotografías JPEG, PNG o WebP. Máximo 10 MB cada una.</p><IncidentPhotoUploader photos={photos} onChange={setPhotos} type="BEFORE"/></section>{error&&<p className="form-error">{error}</p>}<button className="btn btn--primary submit-incident" disabled={submitted||!towerId||!areaId||!categoryId}><Send/>{submitted?<><CheckCircle2/>Registrando…</>:"Reportar incidencia"}</button></form></div>;
}
