import {requireAdmin} from "@/lib/auth/require-admin";import {supabaseServerFetch} from "@/lib/database/verified-request";import {fetchRealVisits} from "@/lib/visits/server";import {z} from "zod";
export const runtime="nodejs";type Context={params:Promise<{visitId:string}>};const actionSchema=z.discriminatedUnion("action",[z.object({action:z.literal("RESCHEDULE"),date:z.string().date(),time:z.string().regex(/^\d{2}:\d{2}$/),reason:z.string().trim().min(3).max(1000)}),z.object({action:z.literal("CANCEL"),reason:z.string().trim().min(3).max(1000)})]);
type Snapshot={sections:{id:string;name:string;items:{id:string;name:string;description?:string;required:boolean}[]}[]};
export async function GET(_:Request,{params}:Context){
  if(!(await requireAdmin()))return Response.json({error:"No autorizado."},{status:403});
  const {visitId}=await params;
  const visit=(await fetchRealVisits()).find(v=>v.id===visitId);
  if(!visit)return Response.json({error:"Visita no encontrada."},{status:404});
  const inspectionResponse=await supabaseServerFetch(`inspections?select=id,template_snapshot,status,progress,started_at,completed_at,overall_condition&visit_id=eq.${visitId}&limit=1`);
  const [inspection]=inspectionResponse.ok?await inspectionResponse.json() as {id:string;template_snapshot:Snapshot;status:string;progress:number;started_at:string;completed_at:string|null;overall_condition:string|null}[]:[];
  if(!inspection)return Response.json({visit,inspection:null});
  const [answerResponse,photoResponse,incidentResponse]=await Promise.all([
    supabaseServerFetch(`inspection_answers?select=id,item_id,condition,observation,responsible,material_needed,priority,updated_at&inspection_id=eq.${inspection.id}`),
    supabaseServerFetch(`inspection_photos?select=id,answer_id&inspection_id=eq.${inspection.id}&deleted_at=is.null`),
    supabaseServerFetch(`incidents?select=id,answer_id,code,status&inspection_id=eq.${inspection.id}`),
  ]);
  if(!answerResponse.ok)console.error("[admin/visit] answers query failed",{visitId,inspectionId:inspection.id,status:answerResponse.status});
  const answers=answerResponse.ok?await answerResponse.json() as {id:string;item_id:string;condition:string;observation:string|null;responsible:string|null;material_needed:string|null;priority:string|null;updated_at:string}[]:[];
  const photos=photoResponse.ok?await photoResponse.json() as {id:string;answer_id:string|null}[]:[];
  const incidents=incidentResponse.ok?await incidentResponse.json() as {id:string;answer_id:string|null;code:string;status:string}[]:[];
  return Response.json({visit,inspection:{id:inspection.id,status:inspection.status,progress:inspection.progress,startedAt:inspection.started_at,completedAt:inspection.completed_at,overallCondition:inspection.overall_condition,sections:inspection.template_snapshot.sections.map(section=>({id:section.id,title:section.name,items:section.items.map(item=>({id:item.id,title:item.name,instructions:item.description??"",required:item.required}))})),answers:Object.fromEntries(answers.map(answer=>[answer.item_id,{condition:answer.condition,observation:answer.observation,responsible:answer.responsible,materialNeeded:answer.material_needed,priority:answer.priority,updatedAt:answer.updated_at,photos:photos.filter(photo=>photo.answer_id===answer.id).map(photo=>({id:photo.id,url:`/api/admin/visits/${visitId}/inspection/photos/${photo.id}`})),incident:incidents.find(incident=>incident.answer_id===answer.id)??null}]))}});
}
export async function PATCH(request:Request,{params}:Context){const actor=await requireAdmin();if(!actor)return Response.json({error:"No autorizado."},{status:403});try{const {visitId}=await params,input=actionSchema.parse(await request.json()),query=new URLSearchParams({select:"id,status,scheduled_date,scheduled_time",id:`eq.${visitId}`,limit:"1"}),currentResponse=await supabaseServerFetch(`visits?${query}`),[current]=currentResponse.ok?await currentResponse.json() as {id:string;status:string;scheduled_date:string;scheduled_time:string}[]:[];if(!current)return Response.json({error:"Visita no encontrada."},{status:404});if(["COMPLETED","CANCELLED"].includes(current.status))return Response.json({error:"Esta visita ya no puede modificarse."},{status:400});if(input.action==="RESCHEDULE"){const update=await supabaseServerFetch(`visits?id=eq.${visitId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({scheduled_date:input.date,scheduled_time:input.time,status:"RESCHEDULED",updated_by_id:actor.id})});if(!update.ok)return Response.json({error:"No se pudo reprogramar la visita."},{status:502});await supabaseServerFetch("visit_schedule_history",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({visit_id:visitId,previous_date:current.scheduled_date,previous_time:current.scheduled_time,new_date:input.date,new_time:input.time,reason:input.reason,changed_by_id:actor.id})})}else{const update=await supabaseServerFetch(`visits?id=eq.${visitId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:"CANCELLED",cancelled_at:new Date().toISOString(),cancelled_by_id:actor.id,cancellation_reason:input.reason,updated_by_id:actor.id})});if(!update.ok)return Response.json({error:"No se pudo cancelar la visita."},{status:502})}return Response.json({success:true})}catch(error){if(error instanceof z.ZodError)return Response.json({error:"Revisa los datos de la acción."},{status:400});return Response.json({error:"No se pudo actualizar la visita."},{status:500})}}

const editSchema=z.object({towerId:z.string().uuid(),supervisorId:z.string().uuid(),scheduledDate:z.string().date(),scheduledTime:z.string().regex(/^\d{2}:\d{2}$/),estimatedDuration:z.number().int().min(15).max(720),visitTypeId:z.string().uuid().optional(),checklistTemplateId:z.string().uuid().optional(),notes:z.string().trim().max(2000).optional(),priority:z.enum(["LOW","MEDIUM","HIGH"]).optional()});
export async function PUT(request:Request,{params}:Context){const actor=await requireAdmin();if(!actor)return Response.json({error:"No autorizado."},{status:403});try{const {visitId}=await params,input=editSchema.parse(await request.json()),currentResponse=await supabaseServerFetch(`visits?select=id,status&id=eq.${visitId}&limit=1`),[current]=currentResponse.ok?await currentResponse.json() as {id:string;status:string}[]:[];if(!current)return Response.json({error:"Visita no encontrada."},{status:404});if(!["SCHEDULED","RESCHEDULED"].includes(current.status))return Response.json({error:"Solo se pueden editar visitas que aún no han iniciado."},{status:409});const assignmentResponse=await supabaseServerFetch(`tower_assignments?select=id&tower_id=eq.${input.towerId}&supervisor_id=eq.${input.supervisorId}&status=eq.ACTIVE&start_date=lte.${input.scheduledDate}&limit=1`);if(!assignmentResponse.ok||(await assignmentResponse.json() as unknown[]).length===0)return Response.json({error:"El supervisor no tiene una asignación activa en esa torre."},{status:400});const dayResponse=await supabaseServerFetch(`visits?select=id,scheduled_time,estimated_duration_minutes&supervisor_id=eq.${input.supervisorId}&scheduled_date=eq.${input.scheduledDate}&status=in.(SCHEDULED,RESCHEDULED,IN_PROGRESS)&id=neq.${visitId}`),start=Number(input.scheduledTime.slice(0,2))*60+Number(input.scheduledTime.slice(3)),end=start+input.estimatedDuration,conflict=(dayResponse.ok?await dayResponse.json() as {scheduled_time:string;estimated_duration_minutes:number}[]:[]).some(visit=>{const other=Number(visit.scheduled_time.slice(0,2))*60+Number(visit.scheduled_time.slice(3));return start<other+visit.estimated_duration_minutes&&end>other});if(conflict)return Response.json({error:"El supervisor ya tiene otra visita durante ese horario."},{status:409});const updated=await supabaseServerFetch(`visits?id=eq.${visitId}`,{method:"PATCH",headers:{"content-type":"application/json",Prefer:"return=representation"},body:JSON.stringify({tower_id:input.towerId,supervisor_id:input.supervisorId,scheduled_date:input.scheduledDate,scheduled_time:input.scheduledTime,estimated_duration_minutes:input.estimatedDuration,visit_type_id:input.visitTypeId||null,checklist_template_id:input.checklistTemplateId||null,notes:input.notes||null,priority:input.priority||null,updated_by_id:actor.id})});if(!updated.ok||(await updated.json() as unknown[]).length===0)return Response.json({error:"No se pudo guardar la visita."},{status:502});return Response.json({success:true})}catch(error){if(error instanceof z.ZodError)return Response.json({error:"Revisa los datos de la visita."},{status:400});return Response.json({error:"No se pudo editar la visita."},{status:500})}}
