"use client";
import { IncidentFilters, type IncidentFilterValue } from "@/components/incidents/incident-filters";
import { IncidentPriorityBadge, IncidentStatusBadge } from "@/components/incidents/incident-badges";
import { listIncidents } from "@/features/incidents/service";
import type { IncidentStatus } from "@/features/incidents/types";
import { AlertOctagon, AlertTriangle, CheckCircle2, Clock3, Eye, ShieldCheck, Timer } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
export default function AdminIncidentsPage(){const [items,setItems]=useState(()=>listIncidents());const [filter,setFilter]=useState<IncidentFilterValue>({query:"",tower:"",priority:"",status:"",date:""});useEffect(()=>{const reload=()=>setItems(listIncidents());window.addEventListener("adcondo:incidents",reload);return()=>window.removeEventListener("adcondo:incidents",reload)},[]);const shown=items.filter(i=>(!filter.query||`${i.code} ${i.towerName} ${i.title}`.toLowerCase().includes(filter.query.toLowerCase()))&&(!filter.tower||i.towerName===filter.tower)&&(!filter.priority||i.priority===filter.priority)&&(!filter.status||i.status===filter.status)&&(!filter.date||i.createdAt.startsWith(filter.date)));const count=(s:IncidentStatus)=>items.filter(i=>i.status===s).length;return <div className="admin-incidents-page"><div className="dashboard-heading"><div><span className="mobile-overline">Control operativo</span><h1>Gestión de incidencias</h1><p>Asigna responsables y controla cada hallazgo hasta su cierre.</p></div></div><section className="admin-incident-kpis"><article><AlertTriangle/><span>Incidencias abiertas<b>{count("OPEN")}</b></span></article><article><AlertOctagon/><span>Incidencias críticas<b>{items.filter(i=>i.priority==="CRITICAL"&&i.status!=="CLOSED").length}</b></span></article><article><Clock3/><span>En proceso<b>{count("IN_PROGRESS")}</b></span></article><article><ShieldCheck/><span>Pendientes de verificación<b>{count("PENDING_VERIFICATION")}</b></span></article><article><CheckCircle2/><span>Resueltas esta semana<b>{count("RESOLVED")}</b></span></article><article><Timer/><span>Tiempo promedio<b>18.4 h</b></span></article></section><IncidentFilters value={filter} onChange={setFilter} towers={[...new Set(items.map(i=>i.towerName))]} showSupervisor showResponsible/><section className="admin-incidents-table"><header><span>Código / Torre</span><span>Problema</span><span>Prioridad</span><span>Estado</span><span>Supervisor</span><span>Responsable</span><span>Tiempo abierta</span><span/></header>{shown.map(item=><article key={item.id}><span><b>{item.code}</b><small>{item.towerName}</small></span><span><b>{item.title}</b><small>{item.area} · {new Date(item.createdAt).toLocaleDateString("es-DO")}</small></span><IncidentPriorityBadge priority={item.priority}/><IncidentStatusBadge status={item.status}/><span>{item.reportedBy}</span><span>{item.assignedTo??"Sin asignar"}</span><span>{Math.max(1,Math.round((Date.now()-new Date(item.createdAt).getTime())/3600000))} h</span><Link href={`/admin/incidencias/${item.id}`}><Eye/>Ver</Link></article>)}</section></div>}
