"use client";
import { InventoryEditor } from "@/components/inventory/inventory-editor";
import { InventoryItemRow } from "@/components/inventory/inventory-item-row";
import { inventoryCategories } from "@/features/inventory/mock-data";
import type { InventoryCategory,TowerInventory } from "@/features/inventory/types";
import { ArrowLeft,ShoppingCart } from "lucide-react";
import Link from "next/link";import { useParams,useRouter } from "next/navigation";import { useCallback,useEffect,useState } from "react";
type TowerOption={id:string;name:string;code:string;sector:string};
export default function TowerInventoryPage(){const {towerId}=useParams<{towerId:string}>();const router=useRouter();const [items,setItems]=useState<TowerInventory[]>([]),[tower,setTower]=useState<TowerOption>(),[editing,setEditing]=useState<TowerInventory>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);const load=useCallback(async()=>{const response=await fetch("/api/inventory",{cache:"no-store"}),data=await response.json() as {inventory?:TowerInventory[];towers?:TowerOption[];error?:string};if(!response.ok)throw new Error(data.error);setItems((data.inventory??[]).filter(item=>item.towerId===towerId));setTower((data.towers??[]).find(item=>item.id===towerId));},[towerId]);useEffect(()=>{load().catch(reason=>setError(reason instanceof Error?reason.message:"No se pudo cargar el inventario."))},[load]);const alertIds=items.filter(i=>i.status==="LOW_STOCK"||i.status==="OUT_OF_STOCK").map(i=>i.inventoryItemId);const save=async(item:TowerInventory)=>{setBusy(true);setError("");try{const form=new FormData();form.set("quantity",String(item.quantity));form.set("recommendedQuantity",String(item.recommendedQuantity));form.set("location",item.location);form.set("observation",item.observation??"");form.set("status",item.status);item.photos.filter(photo=>photo.file).forEach(photo=>form.append("photos",photo.file!));const response=await fetch(`/api/inventory/${item.id}`,{method:"PATCH",body:form}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);await load();setEditing(undefined);}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo guardar la revisión.")}finally{setBusy(false)}};return <><header className="module-heading compact"><div><Link className="back-link" href="/supervisor/inventario"><ArrowLeft/> Inventario</Link><h1>{tower?.name??"Torre residencial"}</h1><p>{tower?.sector} · {tower?.code}</p></div><Link className="btn btn--primary" href={`/supervisor/solicitudes/nueva?towerId=${towerId}&items=${alertIds.join(",")}`}><ShoppingCart/> Solicitar reposición ({alertIds.length})</Link></header>{error&&<p className="form-error">{error}</p>}{(Object.keys(inventoryCategories) as InventoryCategory[]).map(category=>{const group=items.filter(i=>i.category===category);return group.length?<section className="inventory-section card" key={category}><header><h2>{inventoryCategories[category]}</h2><span>{group.length} materiales</span></header>{group.map(item=><InventoryItemRow key={item.id} item={item} onEdit={()=>setEditing(item)}/>)}</section>:null})}{editing&&<InventoryEditor item={editing} onClose={()=>setEditing(undefined)} onSave={save} onRequest={item=>{save(item).then(()=>router.push(`/supervisor/solicitudes/nueva?towerId=${towerId}&items=${item.inventoryItemId}`))}}/>}{busy&&<div className="saving-overlay">Guardando revisión…</div>}</>}
