"use client";
import { InventoryEditor } from "@/components/inventory/inventory-editor";
import { InventoryItemRow } from "@/components/inventory/inventory-item-row";
import { inventoryCategories,inventoryTowers } from "@/features/inventory/mock-data";
import { inventoryByTower,saveInventoryItem } from "@/features/inventory/service";
import type { InventoryCategory,TowerInventory } from "@/features/inventory/types";
import { ArrowLeft,ShoppingCart } from "lucide-react";
import Link from "next/link";import { useParams,useRouter } from "next/navigation";import { useEffect,useState } from "react";
export default function TowerInventoryPage(){const {towerId}=useParams<{towerId:string}>();const router=useRouter();const [items,setItems]=useState<TowerInventory[]>([]);const [editing,setEditing]=useState<TowerInventory>();useEffect(()=>setItems(inventoryByTower(towerId)),[towerId]);const tower=inventoryTowers.find(t=>t.id===towerId);const alertIds=items.filter(i=>i.status==="LOW_STOCK"||i.status==="OUT_OF_STOCK").map(i=>i.inventoryItemId);const save=(item:TowerInventory)=>{saveInventoryItem(item);setItems(inventoryByTower(towerId));setEditing(undefined)};return <><header className="module-heading compact"><div><Link className="back-link" href="/supervisor/inventario"><ArrowLeft/> Inventario</Link><h1>{tower?.name??"Torre residencial"}</h1><p>{tower?.sector} · {tower?.code}</p></div><Link className="btn btn--primary" href={`/supervisor/solicitudes/nueva?towerId=${towerId}&items=${alertIds.join(",")}`}><ShoppingCart/> Solicitar reposición ({alertIds.length})</Link></header>{(Object.keys(inventoryCategories) as InventoryCategory[]).map(category=>{const group=items.filter(i=>i.category===category);return group.length?<section className="inventory-section card" key={category}><header><h2>{inventoryCategories[category]}</h2><span>{group.length} materiales</span></header>{group.map(item=><InventoryItemRow key={item.id} item={item} onEdit={()=>setEditing(item)}/>)}</section>:null})}{editing&&<InventoryEditor item={editing} onClose={()=>setEditing(undefined)} onSave={save} onRequest={item=>{saveInventoryItem(item);router.push(`/supervisor/solicitudes/nueva?towerId=${towerId}&items=${item.inventoryItemId}`)}}/>}</>}
