"use client";
import { TowerCard } from "@/components/towers/tower-card";
import type { Tower } from "@/features/towers/types";
import { Building2, Eye, Plus, Search, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

export default function TowersPage() {
  const [towers, setTowers] = useState<Tower[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [query, setQuery] = useState(""), [status, setStatus] = useState("ALL"), [sector, setSector] = useState("ALL"), [supervisor, setSupervisor] = useState("ALL");
  useEffect(() => { fetch("/api/admin/towers", { cache: "no-store" }).then(async (response) => { const data = await response.json() as { towers?: Tower[]; error?: string }; if (!response.ok) throw new Error(data.error); setTowers(data.towers ?? []); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "No se pudieron cargar las torres.")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => towers.filter((tower) => (status === "ALL" || tower.status === status) && (sector === "ALL" || tower.sector === sector) && (supervisor === "ALL" || tower.supervisors.includes(supervisor)) && `${tower.name} ${tower.code} ${tower.address} ${tower.sector}`.toLowerCase().includes(query.toLowerCase())), [towers, query, status, sector, supervisor]);
  return <><header className="module-heading"><div><span className="eyebrow"><Building2 /> Edificios supervisados</span><h1>Torres residenciales</h1><p>Registra y administra los edificios reales de ADCONDO DEL CARIBE.</p></div><Link className="btn btn--primary" href="/admin/torres/nueva"><Plus /> Nueva torre</Link></header>
    <div className="tower-kpis"><article><Building2 /><span><b>{towers.length}</b>Total de torres</span></article><article><Eye /><span><b>{towers.filter((tower) => tower.status === "ACTIVE").length}</b>Torres activas</span></article><article><ShieldAlert /><span><b>0</b>Con incidencias</span></article><article><Building2 /><span><b>{towers.filter((tower) => tower.supervisors.length > 0).length}</b>Con supervisión</span></article></div>
    <section className="tower-filters card"><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar nombre, código, dirección o sector..." /></label><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">Todos los estados</option>{["ACTIVE", "OBSERVATION", "MAINTENANCE", "INACTIVE"].map((value) => <option key={value}>{value}</option>)}</select><select value={sector} onChange={(event) => setSector(event.target.value)}><option value="ALL">Todos los sectores</option>{[...new Set(towers.map((tower) => tower.sector))].map((value) => <option key={value}>{value}</option>)}</select><select value={supervisor} onChange={(event) => setSupervisor(event.target.value)}><option value="ALL">Todos los supervisores</option>{[...new Set(towers.flatMap((tower) => tower.supervisors))].map((value) => <option key={value}>{value}</option>)}</select></section>
    {loading && <section className="card"><p>Cargando torres reales…</p></section>}{error && <section className="card"><p className="form-error">{error}</p></section>}{!loading && !error && towers.length === 0 && <section className="card empty-state"><Building2 /><h2>Aún no hay torres registradas</h2><p>Puedes crear la primera manualmente cuando tengas su información.</p><Link className="btn btn--primary" href="/admin/torres/nueva">Crear primera torre</Link></section>}
    <div className="tower-card-grid">{filtered.map((tower) => <TowerCard tower={tower} key={tower.id} />)}</div></>;
}
