"use client";
import { seedInventory, seedRequests } from "./mock-data";
import type { MaterialRequest, MaterialRequestStatus, RequestItem, TowerInventory } from "./types";
const INVENTORY_KEY="adcondo:inventory:v1";const REQUEST_KEY="adcondo:material-requests:v1";const clone=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
export function listInventory(){if(typeof window==="undefined")return clone(seedInventory);const raw=localStorage.getItem(INVENTORY_KEY);if(!raw){localStorage.setItem(INVENTORY_KEY,JSON.stringify(seedInventory));return clone(seedInventory)}try{return JSON.parse(raw) as TowerInventory[]}catch{return clone(seedInventory)}}
export function inventoryByTower(towerId:string){return listInventory().filter(item=>item.towerId===towerId)}
export function saveInventoryItem(item:TowerInventory){const items=listInventory();const next=items.map(current=>current.id===item.id?{...item,lastCheckedById:"usr-juan",lastCheckedBy:"Juan Rodríguez",lastCheckedAt:new Date().toISOString()}:current);localStorage.setItem(INVENTORY_KEY,JSON.stringify(next));window.dispatchEvent(new Event("adcondo:inventory"));return next.find(current=>current.id===item.id)!}
export function listRequests(){if(typeof window==="undefined")return clone(seedRequests);const raw=localStorage.getItem(REQUEST_KEY);if(!raw){localStorage.setItem(REQUEST_KEY,JSON.stringify(seedRequests));return clone(seedRequests)}try{return JSON.parse(raw) as MaterialRequest[]}catch{return clone(seedRequests)}}
export function getRequest(id:string){return listRequests().find(request=>request.id===id)??listRequests()[0]}
export function createRequest(towerId:string,towerName:string,towerCode:string,items:RequestItem[],observation:string,status:MaterialRequestStatus="SUBMITTED"){const requests=listRequests();const number=Math.max(...requests.map(r=>Number(r.code.replace(/\D/g,""))),0)+1;const now=new Date().toISOString();const request:MaterialRequest={id:`req-${number}`,code:`SOL-${String(number).padStart(4,"0")}`,towerId,towerName,towerCode,requestedById:"usr-juan",requestedBy:"Juan Rodríguez",status,items,generalObservation:observation,createdAt:now,updatedAt:now,updates:[{id:crypto.randomUUID(),userId:"usr-juan",userName:"Juan Rodríguez",newStatus:status,comment:status==="DRAFT"?"Solicitud guardada como borrador.":"Solicitud creada y enviada.",createdAt:now}]};localStorage.setItem(REQUEST_KEY,JSON.stringify([request,...requests]));window.dispatchEvent(new Event("adcondo:requests"));return request}
const transitions:Record<MaterialRequestStatus,MaterialRequestStatus[]>={DRAFT:["SUBMITTED"],SUBMITTED:["UNDER_REVIEW","REJECTED"],UNDER_REVIEW:["APPROVED","REJECTED"],APPROVED:["PURCHASED"],REJECTED:[],PURCHASED:["DELIVERED"],DELIVERED:[]};
export function updateRequestStatus(id:string,newStatus:MaterialRequestStatus,comment:string){const requests=listRequests();const now=new Date().toISOString();let result=requests[0];const next=requests.map(request=>{if(request.id!==id)return request;if(!transitions[request.status].includes(newStatus))return request;result={...request,status:newStatus,rejectionReason:newStatus==="REJECTED"?comment:request.rejectionReason,updatedAt:now,...(newStatus==="APPROVED"?{approvedAt:now}:{}),...(newStatus==="PURCHASED"?{purchasedAt:now}:{}),...(newStatus==="DELIVERED"?{deliveredAt:now}:{}),updates:[...request.updates,{id:crypto.randomUUID(),userId:"usr-admin",userName:"María Fernández",oldStatus:request.status,newStatus,comment,createdAt:now}]};return result});localStorage.setItem(REQUEST_KEY,JSON.stringify(next));window.dispatchEvent(new Event("adcondo:requests"));return result}
export const inventoryStatusLabels={AVAILABLE:"Disponible",LOW_STOCK:"Bajo stock",OUT_OF_STOCK:"Agotado",NOT_VERIFIED:"No verificado"};export const requestStatusLabels={DRAFT:"Borrador",SUBMITTED:"Enviada",UNDER_REVIEW:"En revisión",APPROVED:"Aprobada",REJECTED:"Rechazada",PURCHASED:"Comprada",DELIVERED:"Entregada"};
